// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lang.flex


 /*  Trabalho de Compiladores - Analisador Léxico.
  *  Kleiton Ewerton de Oliveira - MAT 202065050C
  *  Nikolas Oliver Sales Genesio - MAT 202065072C
  */
  

@SuppressWarnings("fallthrough")
class Lext {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\1\30\1\31\1\32\2\30"+
    "\1\33\2\30\1\34\21\30\1\35\1\36\1\37\1\0"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\43\1\47\1\50\2\43\1\51\1\43\1\52\1\53"+
    "\1\54\1\43\1\55\1\56\1\57\1\60\5\43\1\61"+
    "\1\0\1\62\2\0\5\63\1\64\44\63\1\65\12\63"+
    "\1\65\4\63\1\65\5\63\27\66\1\63\7\66\30\65"+
    "\1\63\10\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\2\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\2\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\2\66\1\65\1\66\1\65\1\66\3\65\2\66\1\65"+
    "\1\66\1\65\2\66\1\65\3\66\2\65\4\66\1\65"+
    "\2\66\1\65\3\66\3\65\2\66\1\65\2\66\1\65"+
    "\1\66\1\65\1\66\1\65\2\66\1\65\1\66\2\65"+
    "\1\66\1\65\2\66\1\65\3\66\1\65\1\66\1\65"+
    "\2\66\2\65\1\67\1\66\3\65\4\67\1\66\1\67"+
    "\1\65\1\66\1\67\1\65\1\66\1\67\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\2\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\2\65\1\66\1\67\1\65\1\66\1\65\3\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\7\65\2\66\1\65\2\66\2\65\1\66\1\65"+
    "\4\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\105\65\1\67\44\65\7\67\2\65\4\63\14\67"+
    "\16\63\5\65\7\63\1\67\1\63\1\67\126\63\1\70"+
    "\52\63\1\66\1\65\1\66\1\65\1\67\1\63\1\66"+
    "\1\65\2\63\4\65\1\63\1\66\6\63\1\66\1\63"+
    "\3\66\1\63\1\66\1\63\2\66\1\65\21\66\1\63"+
    "\11\66\43\65\1\66\2\65\3\66\3\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\5\65\1\66\1\65"+
    "\1\63\1\66\1\65\2\66\2\65\63\66\60\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\10\63\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\2\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\2\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\63\46\66"+
    "\2\63\1\67\6\63\51\65\107\63\33\67\4\63\4\67"+
    "\55\63\53\67\25\63\12\71\4\63\2\67\1\63\143\67"+
    "\1\63\1\67\17\63\2\67\7\63\2\67\12\71\3\67"+
    "\2\63\1\67\20\63\1\67\1\63\36\67\35\63\131\67"+
    "\13\63\1\67\16\63\12\71\41\67\11\63\2\67\4\63"+
    "\1\67\5\63\26\67\4\63\1\67\11\63\1\67\3\63"+
    "\1\67\27\63\31\67\7\63\13\67\65\63\25\67\1\63"+
    "\10\67\106\63\66\67\3\63\1\67\22\63\1\67\7\63"+
    "\12\67\4\63\12\71\1\63\20\67\4\63\10\67\2\63"+
    "\2\67\2\63\26\67\1\63\7\67\1\63\1\67\3\63"+
    "\4\67\3\63\1\67\20\63\1\67\15\63\2\67\1\63"+
    "\3\67\4\63\12\71\2\67\12\63\1\67\10\63\6\67"+
    "\4\63\2\67\2\63\26\67\1\63\7\67\1\63\2\67"+
    "\1\63\2\67\1\63\2\67\37\63\4\67\1\63\1\67"+
    "\7\63\12\71\2\63\3\67\20\63\11\67\1\63\3\67"+
    "\1\63\26\67\1\63\7\67\1\63\2\67\1\63\5\67"+
    "\3\63\1\67\22\63\1\67\17\63\2\67\4\63\12\71"+
    "\11\63\1\67\13\63\10\67\2\63\2\67\2\63\26\67"+
    "\1\63\7\67\1\63\2\67\1\63\5\67\3\63\1\67"+
    "\36\63\2\67\1\63\3\67\4\63\12\71\1\63\1\67"+
    "\21\63\1\67\1\63\6\67\3\63\3\67\1\63\4\67"+
    "\3\63\2\67\1\63\1\67\1\63\2\67\3\63\2\67"+
    "\3\63\3\67\3\63\14\67\26\63\1\67\25\63\12\71"+
    "\25\63\10\67\1\63\3\67\1\63\27\67\1\63\20\67"+
    "\3\63\1\67\32\63\3\67\5\63\2\67\4\63\12\71"+
    "\20\63\1\67\4\63\10\67\1\63\3\67\1\63\27\67"+
    "\1\63\12\67\1\63\5\67\3\63\1\67\40\63\1\67"+
    "\1\63\2\67\4\63\12\71\1\63\2\67\22\63\10\67"+
    "\1\63\3\67\1\63\51\67\2\63\1\67\20\63\1\67"+
    "\5\63\3\67\10\63\3\67\4\63\12\71\12\63\6\67"+
    "\5\63\22\67\3\63\30\67\1\63\11\67\1\63\1\67"+
    "\2\63\7\67\37\63\12\71\21\63\60\67\1\63\2\67"+
    "\14\63\7\67\11\63\12\71\47\63\2\67\1\63\1\67"+
    "\1\63\5\67\1\63\30\67\1\63\1\67\1\63\12\67"+
    "\1\63\2\67\11\63\1\67\2\63\5\67\1\63\1\67"+
    "\11\63\12\71\2\63\4\67\40\63\1\67\37\63\12\71"+
    "\26\63\10\67\1\63\44\67\33\63\5\67\163\63\53\67"+
    "\24\63\1\67\12\71\6\63\6\67\4\63\4\67\3\63"+
    "\1\67\3\63\2\67\7\63\3\67\4\63\15\67\14\63"+
    "\1\67\1\63\12\71\6\63\46\66\1\63\1\66\5\63"+
    "\1\66\2\63\53\65\1\63\1\67\3\65\u0149\67\1\63"+
    "\4\67\2\63\7\67\1\63\1\67\1\63\4\67\2\63"+
    "\51\67\1\63\4\67\2\63\41\67\1\63\4\67\2\63"+
    "\7\67\1\63\1\67\1\63\4\67\2\63\17\67\1\63"+
    "\71\67\1\63\4\67\2\63\103\67\45\63\20\67\20\63"+
    "\126\66\2\63\6\65\3\63\u016c\67\2\63\21\67\1\63"+
    "\32\67\5\63\113\67\6\63\10\67\7\63\15\67\1\63"+
    "\4\67\16\63\22\67\16\63\22\67\16\63\15\67\1\63"+
    "\3\67\17\63\64\67\43\63\1\67\4\63\1\67\3\63"+
    "\12\71\46\63\12\71\6\63\131\67\7\63\5\67\2\63"+
    "\42\67\1\63\1\67\5\63\106\67\12\63\37\67\47\63"+
    "\12\71\36\67\2\63\5\67\13\63\54\67\4\63\32\67"+
    "\6\63\12\71\46\63\27\67\11\63\65\67\53\63\12\71"+
    "\6\63\12\71\15\63\1\67\135\63\57\67\21\63\7\67"+
    "\4\63\12\71\51\63\36\67\15\63\2\67\12\71\54\67"+
    "\32\63\44\67\34\63\12\71\3\63\3\67\12\71\44\67"+
    "\2\63\11\65\7\63\53\66\2\63\3\66\51\63\4\67"+
    "\1\63\6\67\1\63\2\67\3\63\1\67\5\63\300\65"+
    "\100\63\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\11\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\11\65\10\66\6\65\2\63\6\66\2\63\10\65\10\66"+
    "\10\65\10\66\6\65\2\63\6\66\2\63\10\65\1\63"+
    "\1\66\1\63\1\66\1\63\1\66\1\63\1\66\10\65"+
    "\10\66\16\65\2\63\10\65\10\67\10\65\10\67\10\65"+
    "\10\67\5\65\1\63\2\65\4\66\1\67\1\63\1\65"+
    "\3\63\3\65\1\63\2\65\4\66\1\67\3\63\4\65"+
    "\2\63\2\65\4\66\4\63\10\65\5\66\5\63\3\65"+
    "\1\63\2\65\4\66\1\67\53\63\2\64\107\63\1\65"+
    "\15\63\1\65\20\63\15\65\145\63\1\66\4\63\1\66"+
    "\2\63\1\65\3\66\2\65\3\66\1\65\1\63\1\66"+
    "\3\63\5\66\6\63\1\66\1\63\1\66\1\63\1\66"+
    "\1\63\4\66\1\63\1\65\4\66\1\65\4\67\1\65"+
    "\2\63\2\65\2\66\5\63\1\66\4\65\4\63\1\65"+
    "\21\63\20\72\20\70\3\63\1\66\1\65\u0231\63\32\72"+
    "\32\70\26\63\57\66\1\63\57\65\1\63\1\66\1\65"+
    "\3\66\2\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\4\66\1\65\1\66\2\65\1\66\10\65\3\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\2\65\6\63\1\66\1\65\1\66\1\65\3\63"+
    "\1\66\1\65\14\63\46\65\1\63\1\65\5\63\1\65"+
    "\2\63\70\67\7\63\1\67\20\63\27\67\11\63\7\67"+
    "\1\63\7\67\1\63\7\67\1\63\7\67\1\63\7\67"+
    "\1\63\7\67\1\63\7\67\1\63\7\67\120\63\1\67"+
    "\325\63\2\67\52\63\5\67\5\63\2\67\4\63\126\67"+
    "\6\63\3\67\1\63\132\67\1\63\4\67\5\63\53\67"+
    "\1\63\136\67\21\63\33\67\65\63\306\67\112\63\360\67"+
    "\20\63\215\67\103\63\56\67\2\63\15\67\3\63\20\67"+
    "\12\71\2\67\24\63\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\67\20\63\1\67\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\3\65"+
    "\2\63\106\67\61\63\11\67\2\63\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\3\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\66"+
    "\12\65\1\66\1\65\1\66\1\65\2\66\1\65\1\66"+
    "\1\65\1\66\1\65\1\66\1\65\1\66\1\65\1\67"+
    "\2\63\1\66\1\65\1\66\1\65\1\67\1\66\1\65"+
    "\1\66\3\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\1\66\1\65\5\66\1\65"+
    "\5\66\1\65\1\66\1\65\1\66\1\65\1\66\1\65"+
    "\1\66\1\65\1\66\1\65\2\63\1\66\1\65\3\66"+
    "\60\63\1\67\3\65\7\67\1\63\3\67\1\63\4\67"+
    "\1\63\27\67\35\63\64\67\16\63\62\67\34\63\12\71"+
    "\30\63\6\67\3\63\1\67\1\63\2\67\1\63\12\71"+
    "\34\67\12\63\27\67\31\63\35\67\7\63\57\67\34\63"+
    "\1\67\12\71\6\63\5\67\1\63\12\67\12\71\5\67"+
    "\1\63\51\67\27\63\3\67\1\63\10\67\4\63\12\71"+
    "\6\63\27\67\3\63\1\67\3\63\62\67\1\63\1\67"+
    "\3\63\2\67\2\63\5\67\2\63\1\67\1\63\1\67"+
    "\30\63\3\67\2\63\13\67\7\63\3\67\14\63\6\67"+
    "\2\63\6\67\2\63\6\67\11\63\7\67\1\63\7\67"+
    "\1\63\53\65\1\63\14\65\10\63\120\65\43\67\15\63"+
    "\12\71\6\63\244\67\14\63\27\67\4\63\61\67\4\63"+
    "\u0100\64\156\67\2\63\152\67\46\63\7\65\14\63\5\65"+
    "\5\63\1\67\1\63\12\67\1\63\15\67\1\63\5\67"+
    "\1\63\1\67\1\63\2\67\1\63\2\67\1\63\154\67"+
    "\41\63\153\67\22\63\100\67\2\63\66\67\50\63\14\67"+
    "\164\63\5\67\1\63\207\67\23\63\12\71\7\63\32\66"+
    "\6\63\32\65\13\63\131\67\3\63\6\67\2\63\6\67"+
    "\2\63\6\67\2\63\3\67\43\63\14\67\1\63\32\67"+
    "\1\63\23\67\1\63\2\67\1\63\17\67\2\63\16\67"+
    "\42\63\173\67\205\63\35\67\3\63\61\67\57\63\40\67"+
    "\15\63\24\67\1\63\10\67\6\63\46\67\12\63\36\67"+
    "\2\63\44\67\4\63\10\67\60\63\50\66\50\65\116\67"+
    "\2\63\12\71\6\63\44\66\4\63\44\65\4\63\50\67"+
    "\10\63\64\67\234\63\67\67\11\63\26\67\12\63\10\67"+
    "\230\63\6\67\2\63\1\67\1\63\54\67\1\63\2\67"+
    "\3\63\1\67\2\63\27\67\12\63\27\67\11\63\37\67"+
    "\101\63\23\67\1\63\2\67\12\63\26\67\12\63\32\67"+
    "\106\63\70\67\6\63\2\67\100\63\1\67\17\63\4\67"+
    "\1\63\3\67\1\63\35\67\52\63\35\67\3\63\35\67"+
    "\43\63\10\67\1\63\34\67\33\63\66\67\12\63\26\67"+
    "\12\63\23\67\15\63\22\67\156\63\111\67\67\63\63\66"+
    "\15\63\63\65\15\63\44\67\14\63\12\71\306\63\35\67"+
    "\12\63\1\67\10\63\26\67\232\63\27\67\14\63\65\67"+
    "\56\63\12\71\23\63\55\67\40\63\31\67\7\63\12\71"+
    "\11\63\44\67\17\63\12\71\4\63\1\67\13\63\43\67"+
    "\3\63\1\67\14\63\60\67\16\63\4\67\13\63\12\71"+
    "\1\67\1\63\1\67\43\63\22\67\1\63\31\67\124\63"+
    "\7\67\1\63\1\67\1\63\4\67\1\63\17\67\1\63"+
    "\12\67\7\63\57\67\21\63\12\71\13\63\10\67\2\63"+
    "\2\67\2\63\26\67\1\63\7\67\1\63\2\67\1\63"+
    "\5\67\3\63\1\67\22\63\1\67\14\63\5\67\236\63"+
    "\65\67\22\63\4\67\5\63\12\71\5\63\1\67\40\63"+
    "\60\67\24\63\2\67\1\63\1\67\10\63\12\71\246\63"+
    "\57\67\51\63\4\67\44\63\60\67\24\63\1\67\13\63"+
    "\12\71\46\63\53\67\15\63\1\67\7\63\12\71\66\63"+
    "\33\67\25\63\12\71\306\63\54\67\164\63\40\66\40\65"+
    "\12\71\25\63\1\67\240\63\10\67\2\63\47\67\20\63"+
    "\1\67\1\63\1\67\34\63\1\67\12\63\50\67\7\63"+
    "\1\67\25\63\1\67\13\63\56\67\23\63\1\67\42\63"+
    "\71\67\7\63\11\67\1\63\45\67\21\63\1\67\17\63"+
    "\12\71\30\63\36\67\160\63\7\67\1\63\2\67\1\63"+
    "\46\67\25\63\1\67\11\63\12\71\6\63\6\67\1\63"+
    "\2\67\1\63\40\67\16\63\1\67\7\63\12\71\u0136\63"+
    "\23\67\15\63\232\67\346\63\304\67\274\63\57\67\321\63"+
    "\107\67\271\63\71\67\7\63\37\67\1\63\12\71\146\63"+
    "\36\67\22\63\60\67\20\63\4\67\14\63\12\71\11\63"+
    "\25\67\5\63\23\67\260\63\40\66\40\65\200\63\113\67"+
    "\5\63\1\67\102\63\15\67\100\63\2\67\1\63\1\67"+
    "\34\63\370\67\10\63\363\67\15\63\37\67\61\63\3\67"+
    "\21\63\4\67\10\63\u018c\67\4\63\153\67\5\63\15\67"+
    "\3\63\11\67\7\63\12\67\146\63\32\66\32\65\32\66"+
    "\7\65\1\63\22\65\32\66\32\65\1\66\1\63\2\66"+
    "\2\63\1\66\2\63\2\66\2\63\4\66\1\63\10\66"+
    "\4\65\1\63\1\65\1\63\7\65\1\63\13\65\32\66"+
    "\32\65\2\66\1\63\4\66\2\63\10\66\1\63\7\66"+
    "\1\63\32\65\2\66\1\63\4\66\1\63\5\66\1\63"+
    "\1\66\3\63\7\66\1\63\32\65\32\66\32\65\32\66"+
    "\32\65\32\66\32\65\32\66\32\65\32\66\32\65\32\66"+
    "\34\65\2\63\31\66\1\63\31\65\1\63\6\65\31\66"+
    "\1\63\31\65\1\63\6\65\31\66\1\63\31\65\1\63"+
    "\6\65\31\66\1\63\31\65\1\63\6\65\31\66\1\63"+
    "\31\65\1\63\6\65\1\66\1\65\2\63\62\71\55\67"+
    "\12\63\7\67\2\63\12\71\4\63\1\67\u0171\63\54\67"+
    "\4\63\12\71\6\63\305\67\73\63\42\66\42\65\7\63"+
    "\1\67\4\63\12\71\246\63\4\67\1\63\33\67\1\63"+
    "\2\67\1\63\1\67\2\63\1\67\1\63\12\67\1\63"+
    "\4\67\1\63\1\67\1\63\1\67\6\63\1\67\4\63"+
    "\1\67\1\63\1\67\1\63\1\67\1\63\3\67\1\63"+
    "\2\67\1\63\1\67\2\63\1\67\1\63\1\67\1\63"+
    "\1\67\1\63\1\67\1\63\1\67\1\63\2\67\1\63"+
    "\1\67\2\63\4\67\1\63\7\67\1\63\4\67\1\63"+
    "\4\67\1\63\1\67\1\63\12\67\1\63\21\67\5\63"+
    "\3\67\1\63\5\67\1\63\21\67\164\63\32\72\6\63"+
    "\32\72\6\63\32\72\166\63\327\67\51\63\65\67\13\63"+
    "\336\67\2\63\u0182\67\16\63\u0131\67\37\63\36\67\342\63";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\5\23\1\24\1\25\11\26"+
    "\1\27\1\30\1\31\1\1\1\31\1\32\1\33\4\0"+
    "\1\34\1\35\1\36\4\23\3\26\1\37\5\26\1\40"+
    "\1\41\2\42\3\23\1\43\11\26\1\44\1\45\1\23"+
    "\1\46\1\47\2\26\1\50\1\26\1\51\1\26\1\52"+
    "\1\53\1\54\1\26\1\55\2\26\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\166\0\261\0\354\0\166\0\u0127"+
    "\0\u0162\0\166\0\166\0\166\0\166\0\166\0\u019d\0\u01d8"+
    "\0\166\0\u0213\0\u024e\0\166\0\166\0\u0289\0\166\0\u02c4"+
    "\0\u02ff\0\u033a\0\u0375\0\u03b0\0\166\0\166\0\u03eb\0\u0426"+
    "\0\u0461\0\u049c\0\u04d7\0\u0512\0\u054d\0\u0588\0\u05c3\0\u05fe"+
    "\0\166\0\166\0\u0639\0\u0674\0\166\0\166\0\u06af\0\u06ea"+
    "\0\u0725\0\u01d8\0\u01d8\0\166\0\166\0\u0760\0\u079b\0\u07d6"+
    "\0\u0811\0\u084c\0\u0887\0\u08c2\0\u03eb\0\u08fd\0\u0938\0\u0973"+
    "\0\u09ae\0\u09e9\0\166\0\166\0\166\0\u06af\0\u0a24\0\u0a5f"+
    "\0\u0a9a\0\u02c4\0\u0ad5\0\u0b10\0\u0b4b\0\u0b86\0\u0bc1\0\u0bfc"+
    "\0\u0c37\0\u0c72\0\u0cad\0\u02c4\0\u02c4\0\u0ce8\0\u03eb\0\u03eb"+
    "\0\u0d23\0\u0d5e\0\u03eb\0\u0d99\0\u03eb\0\u0dd4\0\u03eb\0\u02c4"+
    "\0\u03eb\0\u0e0f\0\u03eb\0\u0e4a\0\u0e85\0\u03eb\0\u03eb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\3\1\36\1\3"+
    "\3\37\1\40\1\41\1\42\1\37\1\43\1\37\1\44"+
    "\1\37\1\45\1\46\1\37\1\47\1\37\1\50\1\51"+
    "\2\3\1\37\1\30\1\3\1\37\1\22\1\30\17\52"+
    "\1\53\41\52\1\54\1\3\10\52\75\0\1\4\116\0"+
    "\1\55\54\0\1\56\62\0\36\57\1\60\24\57\27\0"+
    "\1\61\1\62\1\0\1\22\46\0\1\22\23\0\1\63"+
    "\46\0\1\63\21\0\1\62\1\0\1\22\46\0\1\22"+
    "\24\0\1\64\75\0\1\65\66\0\1\30\5\0\5\30"+
    "\3\0\21\30\4\0\3\30\1\0\1\30\23\0\1\30"+
    "\5\0\5\30\3\0\13\30\1\66\5\30\4\0\3\30"+
    "\1\0\1\30\23\0\1\30\5\0\5\30\3\0\7\30"+
    "\1\67\11\30\4\0\3\30\1\0\1\30\23\0\1\30"+
    "\5\0\5\30\3\0\11\30\1\70\7\30\4\0\3\30"+
    "\1\0\1\30\23\0\1\30\5\0\5\30\3\0\12\30"+
    "\1\71\6\30\4\0\3\30\1\0\1\30\23\0\1\37"+
    "\5\0\5\37\3\0\21\37\4\0\3\37\1\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\1\37\1\72\17\37"+
    "\4\0\3\37\1\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\11\37\1\73\7\37\4\0\3\37\1\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\1\37\1\74\17\37"+
    "\4\0\3\37\1\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\6\37\1\75\10\37\1\76\1\37\4\0\3\37"+
    "\1\0\1\37\23\0\1\37\5\0\5\37\3\0\20\37"+
    "\1\77\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\15\37\1\100\3\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\5\37\1\101"+
    "\13\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\15\37\1\102\3\37\4\0\3\37\1\0"+
    "\1\37\20\0\1\103\135\0\1\104\27\0\1\104\64\0"+
    "\1\105\72\0\1\106\24\0\1\57\3\0\1\57\7\0"+
    "\1\57\2\0\1\57\1\0\1\57\13\0\2\61\1\4"+
    "\2\0\1\5\56\61\1\0\6\61\22\0\1\30\5\0"+
    "\5\30\3\0\13\30\1\107\5\30\4\0\3\30\1\0"+
    "\1\30\23\0\1\30\5\0\5\30\3\0\1\30\1\110"+
    "\17\30\4\0\3\30\1\0\1\30\23\0\1\30\5\0"+
    "\5\30\3\0\13\30\1\111\5\30\4\0\3\30\1\0"+
    "\1\30\23\0\1\30\5\0\5\30\3\0\17\30\1\112"+
    "\1\30\4\0\3\30\1\0\1\30\23\0\1\37\5\0"+
    "\5\37\3\0\17\37\1\113\1\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\16\37\1\114"+
    "\2\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\11\37\1\115\7\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\5\37\1\116"+
    "\13\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\11\37\1\117\7\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\10\37\1\120"+
    "\10\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\1\37\1\121\15\37\1\122\1\37\4\0"+
    "\3\37\1\0\1\37\23\0\1\37\5\0\5\37\3\0"+
    "\20\37\1\123\4\0\3\37\1\0\1\37\23\0\1\30"+
    "\5\0\5\30\3\0\11\30\1\124\7\30\4\0\3\30"+
    "\1\0\1\30\23\0\1\30\5\0\5\30\3\0\15\30"+
    "\1\125\3\30\4\0\3\30\1\0\1\30\23\0\1\30"+
    "\5\0\5\30\3\0\1\30\1\126\17\30\4\0\3\30"+
    "\1\0\1\30\23\0\1\37\5\0\5\37\3\0\1\37"+
    "\1\127\17\37\4\0\3\37\1\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\5\37\1\130\13\37\4\0\3\37"+
    "\1\0\1\37\23\0\1\37\5\0\5\37\3\0\16\37"+
    "\1\131\2\37\4\0\3\37\1\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\15\37\1\132\3\37\4\0\3\37"+
    "\1\0\1\37\23\0\1\37\5\0\5\37\3\0\11\37"+
    "\1\133\7\37\4\0\3\37\1\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\12\37\1\134\6\37\4\0\3\37"+
    "\1\0\1\37\23\0\1\37\5\0\5\37\3\0\4\37"+
    "\1\135\14\37\4\0\3\37\1\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\20\37\1\136\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\5\37\1\137"+
    "\13\37\4\0\3\37\1\0\1\37\23\0\1\30\5\0"+
    "\5\30\3\0\17\30\1\140\1\30\4\0\3\30\1\0"+
    "\1\30\23\0\1\37\5\0\5\37\3\0\5\37\1\141"+
    "\13\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\1\37\1\142\17\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\17\37\1\143"+
    "\1\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\15\37\1\144\3\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\17\37\1\145"+
    "\1\37\4\0\3\37\1\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\12\37\1\146\6\37\4\0\3\37\1\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\5\37\1\147"+
    "\13\37\4\0\3\37\1\0\1\37\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3776];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\5\11\2\1\1\11"+
    "\2\1\2\11\1\1\1\11\5\1\2\11\12\1\2\11"+
    "\2\1\2\11\4\0\1\1\2\11\15\1\3\11\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    /* Código arbitrário pode ser inserido diretamente no analisador dessa forma. 
     * Aqui podemos declarar variáveis e métodos adicionais que julgarmos necessários. 
     */
    private int ntk;
    
    public int readedTokens(){
       return ntk;
    }
    private Token symbol(TOKEN_TYPE t) {
        ntk++;
        return new Token(t, yytext(), yyline+1, yycolumn+1);
        
    }
    private Token symbol(TOKEN_TYPE t, Object value) {
        ntk++;
        return new Token(t, value, yyline+1, yycolumn+1);
    }
    
    private void incTks() { ++ntk; }
    
    private int numTokens() { return ntk; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lext(java.io.Reader in) {
      ntk = 0; // Isto é copiado direto no construtor do lexer. 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
          // fall through
          case 48: break;
          case 2:
            { 
            }
          // fall through
          case 49: break;
          case 3:
            { return symbol(TOKEN_TYPE.NOT);
            }
          // fall through
          case 50: break;
          case 4:
            { return symbol(TOKEN_TYPE.MOD);
            }
          // fall through
          case 51: break;
          case 5:
            { return symbol(TOKEN_TYPE.OPT);
            }
          // fall through
          case 52: break;
          case 6:
            { return symbol(TOKEN_TYPE.CPT);
            }
          // fall through
          case 53: break;
          case 7:
            { return symbol(TOKEN_TYPE.TIMES);
            }
          // fall through
          case 54: break;
          case 8:
            { return symbol(TOKEN_TYPE.PLUS);
            }
          // fall through
          case 55: break;
          case 9:
            { return symbol(TOKEN_TYPE.CMA);
            }
          // fall through
          case 56: break;
          case 10:
            { return symbol(TOKEN_TYPE.MINUS);
            }
          // fall through
          case 57: break;
          case 11:
            { return symbol(TOKEN_TYPE.DOT);
            }
          // fall through
          case 58: break;
          case 12:
            { return symbol(TOKEN_TYPE.DIV);
            }
          // fall through
          case 59: break;
          case 13:
            { System.out.print("INT: "); return symbol(TOKEN_TYPE.VAL_INT, Integer.parseInt(yytext()));
            }
          // fall through
          case 60: break;
          case 14:
            { return symbol(TOKEN_TYPE.DDOT);
            }
          // fall through
          case 61: break;
          case 15:
            { return symbol(TOKEN_TYPE.SEMI);
            }
          // fall through
          case 62: break;
          case 16:
            { return symbol(TOKEN_TYPE.LT);
            }
          // fall through
          case 63: break;
          case 17:
            { return symbol(TOKEN_TYPE.EQ);
            }
          // fall through
          case 64: break;
          case 18:
            { return symbol(TOKEN_TYPE.BT);
            }
          // fall through
          case 65: break;
          case 19:
            { System.out.print("TYPE: "); return symbol(TOKEN_TYPE.TYPE);
            }
          // fall through
          case 66: break;
          case 20:
            { return symbol(TOKEN_TYPE.OCT);
            }
          // fall through
          case 67: break;
          case 21:
            { return symbol(TOKEN_TYPE.CCT);
            }
          // fall through
          case 68: break;
          case 22:
            { System.out.print("ID: "); return symbol(TOKEN_TYPE.ID);
            }
          // fall through
          case 69: break;
          case 23:
            { return symbol(TOKEN_TYPE.OCV);
            }
          // fall through
          case 70: break;
          case 24:
            { return symbol(TOKEN_TYPE.CCV);
            }
          // fall through
          case 71: break;
          case 25:
            { /* Ignora os caracteres dentro do bloco de comentário */
            }
          // fall through
          case 72: break;
          case 26:
            { return symbol(TOKEN_TYPE.NEQ);
            }
          // fall through
          case 73: break;
          case 27:
            { return symbol(TOKEN_TYPE.AND);
            }
          // fall through
          case 74: break;
          case 28:
            { System.out.print("FLOAT: "); return symbol(TOKEN_TYPE.VAL_FLOAT, Float.parseFloat(yytext()));
            }
          // fall through
          case 75: break;
          case 29:
            { return symbol(TOKEN_TYPE.DDDOT);
            }
          // fall through
          case 76: break;
          case 30:
            { return symbol(TOKEN_TYPE.EQEQ);
            }
          // fall through
          case 77: break;
          case 31:
            { return symbol(TOKEN_TYPE.IF);
            }
          // fall through
          case 78: break;
          case 32:
            { yybegin(COMMENT);
            }
          // fall through
          case 79: break;
          case 33:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 80: break;
          case 34:
            { return symbol(TOKEN_TYPE.LITERAL_CARACTERE);
            }
          // fall through
          case 81: break;
          case 35:
            { return symbol(TOKEN_TYPE.INT);
            }
          // fall through
          case 82: break;
          case 36:
            { return symbol(TOKEN_TYPE.BOOL);
            }
          // fall through
          case 83: break;
          case 37:
            { return symbol(TOKEN_TYPE.CHAR);
            }
          // fall through
          case 84: break;
          case 38:
            { return symbol(TOKEN_TYPE.DATA);
            }
          // fall through
          case 85: break;
          case 39:
            { return symbol(TOKEN_TYPE.ELSE);
            }
          // fall through
          case 86: break;
          case 40:
            { return symbol(TOKEN_TYPE.NULL);
            }
          // fall through
          case 87: break;
          case 41:
            { return symbol(TOKEN_TYPE.READ);
            }
          // fall through
          case 88: break;
          case 42:
            { return symbol(TOKEN_TYPE.TRUE);
            }
          // fall through
          case 89: break;
          case 43:
            { return symbol(TOKEN_TYPE.FLOAT);
            }
          // fall through
          case 90: break;
          case 44:
            { return symbol(TOKEN_TYPE.FALSE);
            }
          // fall through
          case 91: break;
          case 45:
            { return symbol(TOKEN_TYPE.PRINT);
            }
          // fall through
          case 92: break;
          case 46:
            { return symbol(TOKEN_TYPE.RET);
            }
          // fall through
          case 93: break;
          case 47:
            { return symbol(TOKEN_TYPE.ITERATE);
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
