// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lang.flex


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  

@SuppressWarnings("fallthrough")
class Lext {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\1\30\1\31\1\32\2\30"+
    "\1\33\2\30\1\34\21\30\1\35\1\36\1\37\1\0"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\43\1\47\1\50\2\43\1\51\1\43\1\52\1\53"+
    "\1\54\1\43\1\55\1\56\1\57\1\60\5\43\1\61"+
    "\1\0\1\62\2\0\5\63\1\64\44\63\1\43\12\63"+
    "\1\43\4\63\1\43\5\63\27\30\1\63\7\30\30\43"+
    "\1\63\10\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\2\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\2\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\2\30\1\43\1\30\1\43\1\30\3\43\2\30\1\43"+
    "\1\30\1\43\2\30\1\43\3\30\2\43\4\30\1\43"+
    "\2\30\1\43\3\30\3\43\2\30\1\43\2\30\1\43"+
    "\1\30\1\43\1\30\1\43\2\30\1\43\1\30\2\43"+
    "\1\30\1\43\2\30\1\43\3\30\1\43\1\30\1\43"+
    "\2\30\2\43\1\40\1\30\3\43\4\40\1\30\1\40"+
    "\1\43\1\30\1\40\1\43\1\30\1\40\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\2\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\2\43\1\30\1\40\1\43\1\30\1\43\3\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\7\43\2\30\1\43\2\30\2\43\1\30\1\43"+
    "\4\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\105\43\1\40\44\43\7\40\2\43\4\63\14\40"+
    "\16\63\5\43\7\63\1\40\1\63\1\40\126\63\1\65"+
    "\52\63\1\30\1\43\1\30\1\43\1\40\1\63\1\30"+
    "\1\43\2\63\4\43\1\63\1\30\6\63\1\30\1\63"+
    "\3\30\1\63\1\30\1\63\2\30\1\43\21\30\1\63"+
    "\11\30\43\43\1\30\2\43\3\30\3\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\5\43\1\30\1\43"+
    "\1\63\1\30\1\43\2\30\2\43\63\30\60\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\10\63\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\2\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\2\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\63\46\30"+
    "\2\63\1\40\6\63\51\43\107\63\33\40\4\63\4\40"+
    "\55\63\53\40\25\63\12\66\4\63\2\40\1\63\143\40"+
    "\1\63\1\40\17\63\2\40\7\63\2\40\12\66\3\40"+
    "\2\63\1\40\20\63\1\40\1\63\36\40\35\63\131\40"+
    "\13\63\1\40\16\63\12\66\41\40\11\63\2\40\4\63"+
    "\1\40\5\63\26\40\4\63\1\40\11\63\1\40\3\63"+
    "\1\40\27\63\31\40\7\63\13\40\65\63\25\40\1\63"+
    "\10\40\106\63\66\40\3\63\1\40\22\63\1\40\7\63"+
    "\12\40\4\63\12\66\1\63\20\40\4\63\10\40\2\63"+
    "\2\40\2\63\26\40\1\63\7\40\1\63\1\40\3\63"+
    "\4\40\3\63\1\40\20\63\1\40\15\63\2\40\1\63"+
    "\3\40\4\63\12\66\2\40\12\63\1\40\10\63\6\40"+
    "\4\63\2\40\2\63\26\40\1\63\7\40\1\63\2\40"+
    "\1\63\2\40\1\63\2\40\37\63\4\40\1\63\1\40"+
    "\7\63\12\66\2\63\3\40\20\63\11\40\1\63\3\40"+
    "\1\63\26\40\1\63\7\40\1\63\2\40\1\63\5\40"+
    "\3\63\1\40\22\63\1\40\17\63\2\40\4\63\12\66"+
    "\11\63\1\40\13\63\10\40\2\63\2\40\2\63\26\40"+
    "\1\63\7\40\1\63\2\40\1\63\5\40\3\63\1\40"+
    "\36\63\2\40\1\63\3\40\4\63\12\66\1\63\1\40"+
    "\21\63\1\40\1\63\6\40\3\63\3\40\1\63\4\40"+
    "\3\63\2\40\1\63\1\40\1\63\2\40\3\63\2\40"+
    "\3\63\3\40\3\63\14\40\26\63\1\40\25\63\12\66"+
    "\25\63\10\40\1\63\3\40\1\63\27\40\1\63\20\40"+
    "\3\63\1\40\32\63\3\40\5\63\2\40\4\63\12\66"+
    "\20\63\1\40\4\63\10\40\1\63\3\40\1\63\27\40"+
    "\1\63\12\40\1\63\5\40\3\63\1\40\40\63\1\40"+
    "\1\63\2\40\4\63\12\66\1\63\2\40\22\63\10\40"+
    "\1\63\3\40\1\63\51\40\2\63\1\40\20\63\1\40"+
    "\5\63\3\40\10\63\3\40\4\63\12\66\12\63\6\40"+
    "\5\63\22\40\3\63\30\40\1\63\11\40\1\63\1\40"+
    "\2\63\7\40\37\63\12\66\21\63\60\40\1\63\2\40"+
    "\14\63\7\40\11\63\12\66\47\63\2\40\1\63\1\40"+
    "\1\63\5\40\1\63\30\40\1\63\1\40\1\63\12\40"+
    "\1\63\2\40\11\63\1\40\2\63\5\40\1\63\1\40"+
    "\11\63\12\66\2\63\4\40\40\63\1\40\37\63\12\66"+
    "\26\63\10\40\1\63\44\40\33\63\5\40\163\63\53\40"+
    "\24\63\1\40\12\66\6\63\6\40\4\63\4\40\3\63"+
    "\1\40\3\63\2\40\7\63\3\40\4\63\15\40\14\63"+
    "\1\40\1\63\12\66\6\63\46\30\1\63\1\30\5\63"+
    "\1\30\2\63\53\43\1\63\1\40\3\43\u0149\40\1\63"+
    "\4\40\2\63\7\40\1\63\1\40\1\63\4\40\2\63"+
    "\51\40\1\63\4\40\2\63\41\40\1\63\4\40\2\63"+
    "\7\40\1\63\1\40\1\63\4\40\2\63\17\40\1\63"+
    "\71\40\1\63\4\40\2\63\103\40\45\63\20\40\20\63"+
    "\126\30\2\63\6\43\3\63\u016c\40\2\63\21\40\1\63"+
    "\32\40\5\63\113\40\6\63\10\40\7\63\15\40\1\63"+
    "\4\40\16\63\22\40\16\63\22\40\16\63\15\40\1\63"+
    "\3\40\17\63\64\40\43\63\1\40\4\63\1\40\3\63"+
    "\12\66\46\63\12\66\6\63\131\40\7\63\5\40\2\63"+
    "\42\40\1\63\1\40\5\63\106\40\12\63\37\40\47\63"+
    "\12\66\36\40\2\63\5\40\13\63\54\40\4\63\32\40"+
    "\6\63\12\66\46\63\27\40\11\63\65\40\53\63\12\66"+
    "\6\63\12\66\15\63\1\40\135\63\57\40\21\63\7\40"+
    "\4\63\12\66\51\63\36\40\15\63\2\40\12\66\54\40"+
    "\32\63\44\40\34\63\12\66\3\63\3\40\12\66\44\40"+
    "\2\63\11\43\7\63\53\30\2\63\3\30\51\63\4\40"+
    "\1\63\6\40\1\63\2\40\3\63\1\40\5\63\300\43"+
    "\100\63\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\11\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\11\43\10\30\6\43\2\63\6\30\2\63\10\43\10\30"+
    "\10\43\10\30\6\43\2\63\6\30\2\63\10\43\1\63"+
    "\1\30\1\63\1\30\1\63\1\30\1\63\1\30\10\43"+
    "\10\30\16\43\2\63\10\43\10\40\10\43\10\40\10\43"+
    "\10\40\5\43\1\63\2\43\4\30\1\40\1\63\1\43"+
    "\3\63\3\43\1\63\2\43\4\30\1\40\3\63\4\43"+
    "\2\63\2\43\4\30\4\63\10\43\5\30\5\63\3\43"+
    "\1\63\2\43\4\30\1\40\53\63\2\64\107\63\1\43"+
    "\15\63\1\43\20\63\15\43\145\63\1\30\4\63\1\30"+
    "\2\63\1\43\3\30\2\43\3\30\1\43\1\63\1\30"+
    "\3\63\5\30\6\63\1\30\1\63\1\30\1\63\1\30"+
    "\1\63\4\30\1\63\1\43\4\30\1\43\4\40\1\43"+
    "\2\63\2\43\2\30\5\63\1\30\4\43\4\63\1\43"+
    "\21\63\20\67\20\65\3\63\1\30\1\43\u0231\63\32\67"+
    "\32\65\26\63\57\30\1\63\57\43\1\63\1\30\1\43"+
    "\3\30\2\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\4\30\1\43\1\30\2\43\1\30\10\43\3\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\2\43\6\63\1\30\1\43\1\30\1\43\3\63"+
    "\1\30\1\43\14\63\46\43\1\63\1\43\5\63\1\43"+
    "\2\63\70\40\7\63\1\40\20\63\27\40\11\63\7\40"+
    "\1\63\7\40\1\63\7\40\1\63\7\40\1\63\7\40"+
    "\1\63\7\40\1\63\7\40\1\63\7\40\120\63\1\40"+
    "\325\63\2\40\52\63\5\40\5\63\2\40\4\63\126\40"+
    "\6\63\3\40\1\63\132\40\1\63\4\40\5\63\53\40"+
    "\1\63\136\40\21\63\33\40\65\63\306\40\112\63\360\40"+
    "\20\63\215\40\103\63\56\40\2\63\15\40\3\63\20\40"+
    "\12\66\2\40\24\63\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\40\20\63\1\40\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\3\43"+
    "\2\63\106\40\61\63\11\40\2\63\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\3\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\30"+
    "\12\43\1\30\1\43\1\30\1\43\2\30\1\43\1\30"+
    "\1\43\1\30\1\43\1\30\1\43\1\30\1\43\1\40"+
    "\2\63\1\30\1\43\1\30\1\43\1\40\1\30\1\43"+
    "\1\30\3\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\1\30\1\43\5\30\1\43"+
    "\5\30\1\43\1\30\1\43\1\30\1\43\1\30\1\43"+
    "\1\30\1\43\1\30\1\43\2\63\1\30\1\43\3\30"+
    "\60\63\1\40\3\43\7\40\1\63\3\40\1\63\4\40"+
    "\1\63\27\40\35\63\64\40\16\63\62\40\34\63\12\66"+
    "\30\63\6\40\3\63\1\40\1\63\2\40\1\63\12\66"+
    "\34\40\12\63\27\40\31\63\35\40\7\63\57\40\34\63"+
    "\1\40\12\66\6\63\5\40\1\63\12\40\12\66\5\40"+
    "\1\63\51\40\27\63\3\40\1\63\10\40\4\63\12\66"+
    "\6\63\27\40\3\63\1\40\3\63\62\40\1\63\1\40"+
    "\3\63\2\40\2\63\5\40\2\63\1\40\1\63\1\40"+
    "\30\63\3\40\2\63\13\40\7\63\3\40\14\63\6\40"+
    "\2\63\6\40\2\63\6\40\11\63\7\40\1\63\7\40"+
    "\1\63\53\43\1\63\14\43\10\63\120\43\43\40\15\63"+
    "\12\66\6\63\244\40\14\63\27\40\4\63\61\40\4\63"+
    "\u0100\64\156\40\2\63\152\40\46\63\7\43\14\63\5\43"+
    "\5\63\1\40\1\63\12\40\1\63\15\40\1\63\5\40"+
    "\1\63\1\40\1\63\2\40\1\63\2\40\1\63\154\40"+
    "\41\63\153\40\22\63\100\40\2\63\66\40\50\63\14\40"+
    "\164\63\5\40\1\63\207\40\23\63\12\66\7\63\32\30"+
    "\6\63\32\43\13\63\131\40\3\63\6\40\2\63\6\40"+
    "\2\63\6\40\2\63\3\40\43\63\14\40\1\63\32\40"+
    "\1\63\23\40\1\63\2\40\1\63\17\40\2\63\16\40"+
    "\42\63\173\40\205\63\35\40\3\63\61\40\57\63\40\40"+
    "\15\63\24\40\1\63\10\40\6\63\46\40\12\63\36\40"+
    "\2\63\44\40\4\63\10\40\60\63\50\30\50\43\116\40"+
    "\2\63\12\66\6\63\44\30\4\63\44\43\4\63\50\40"+
    "\10\63\64\40\234\63\67\40\11\63\26\40\12\63\10\40"+
    "\230\63\6\40\2\63\1\40\1\63\54\40\1\63\2\40"+
    "\3\63\1\40\2\63\27\40\12\63\27\40\11\63\37\40"+
    "\101\63\23\40\1\63\2\40\12\63\26\40\12\63\32\40"+
    "\106\63\70\40\6\63\2\40\100\63\1\40\17\63\4\40"+
    "\1\63\3\40\1\63\35\40\52\63\35\40\3\63\35\40"+
    "\43\63\10\40\1\63\34\40\33\63\66\40\12\63\26\40"+
    "\12\63\23\40\15\63\22\40\156\63\111\40\67\63\63\30"+
    "\15\63\63\43\15\63\44\40\14\63\12\66\306\63\35\40"+
    "\12\63\1\40\10\63\26\40\232\63\27\40\14\63\65\40"+
    "\56\63\12\66\23\63\55\40\40\63\31\40\7\63\12\66"+
    "\11\63\44\40\17\63\12\66\4\63\1\40\13\63\43\40"+
    "\3\63\1\40\14\63\60\40\16\63\4\40\13\63\12\66"+
    "\1\40\1\63\1\40\43\63\22\40\1\63\31\40\124\63"+
    "\7\40\1\63\1\40\1\63\4\40\1\63\17\40\1\63"+
    "\12\40\7\63\57\40\21\63\12\66\13\63\10\40\2\63"+
    "\2\40\2\63\26\40\1\63\7\40\1\63\2\40\1\63"+
    "\5\40\3\63\1\40\22\63\1\40\14\63\5\40\236\63"+
    "\65\40\22\63\4\40\5\63\12\66\5\63\1\40\40\63"+
    "\60\40\24\63\2\40\1\63\1\40\10\63\12\66\246\63"+
    "\57\40\51\63\4\40\44\63\60\40\24\63\1\40\13\63"+
    "\12\66\46\63\53\40\15\63\1\40\7\63\12\66\66\63"+
    "\33\40\25\63\12\66\306\63\54\40\164\63\40\30\40\43"+
    "\12\66\25\63\1\40\240\63\10\40\2\63\47\40\20\63"+
    "\1\40\1\63\1\40\34\63\1\40\12\63\50\40\7\63"+
    "\1\40\25\63\1\40\13\63\56\40\23\63\1\40\42\63"+
    "\71\40\7\63\11\40\1\63\45\40\21\63\1\40\17\63"+
    "\12\66\30\63\36\40\160\63\7\40\1\63\2\40\1\63"+
    "\46\40\25\63\1\40\11\63\12\66\6\63\6\40\1\63"+
    "\2\40\1\63\40\40\16\63\1\40\7\63\12\66\u0136\63"+
    "\23\40\15\63\232\40\346\63\304\40\274\63\57\40\321\63"+
    "\107\40\271\63\71\40\7\63\37\40\1\63\12\66\146\63"+
    "\36\40\22\63\60\40\20\63\4\40\14\63\12\66\11\63"+
    "\25\40\5\63\23\40\260\63\40\30\40\43\200\63\113\40"+
    "\5\63\1\40\102\63\15\40\100\63\2\40\1\63\1\40"+
    "\34\63\370\40\10\63\363\40\15\63\37\40\61\63\3\40"+
    "\21\63\4\40\10\63\u018c\40\4\63\153\40\5\63\15\40"+
    "\3\63\11\40\7\63\12\40\146\63\32\30\32\43\32\30"+
    "\7\43\1\63\22\43\32\30\32\43\1\30\1\63\2\30"+
    "\2\63\1\30\2\63\2\30\2\63\4\30\1\63\10\30"+
    "\4\43\1\63\1\43\1\63\7\43\1\63\13\43\32\30"+
    "\32\43\2\30\1\63\4\30\2\63\10\30\1\63\7\30"+
    "\1\63\32\43\2\30\1\63\4\30\1\63\5\30\1\63"+
    "\1\30\3\63\7\30\1\63\32\43\32\30\32\43\32\30"+
    "\32\43\32\30\32\43\32\30\32\43\32\30\32\43\32\30"+
    "\34\43\2\63\31\30\1\63\31\43\1\63\6\43\31\30"+
    "\1\63\31\43\1\63\6\43\31\30\1\63\31\43\1\63"+
    "\6\43\31\30\1\63\31\43\1\63\6\43\31\30\1\63"+
    "\31\43\1\63\6\43\1\30\1\43\2\63\62\66\55\40"+
    "\12\63\7\40\2\63\12\66\4\63\1\40\u0171\63\54\40"+
    "\4\63\12\66\6\63\305\40\73\63\42\30\42\43\7\63"+
    "\1\40\4\63\12\66\246\63\4\40\1\63\33\40\1\63"+
    "\2\40\1\63\1\40\2\63\1\40\1\63\12\40\1\63"+
    "\4\40\1\63\1\40\1\63\1\40\6\63\1\40\4\63"+
    "\1\40\1\63\1\40\1\63\1\40\1\63\3\40\1\63"+
    "\2\40\1\63\1\40\2\63\1\40\1\63\1\40\1\63"+
    "\1\40\1\63\1\40\1\63\1\40\1\63\2\40\1\63"+
    "\1\40\2\63\4\40\1\63\7\40\1\63\4\40\1\63"+
    "\4\40\1\63\1\40\1\63\12\40\1\63\21\40\5\63"+
    "\3\40\1\63\5\40\1\63\21\40\164\63\32\67\6\63"+
    "\32\67\6\63\32\67\166\63\327\40\51\63\65\40\13\63"+
    "\336\40\2\63\u0182\40\16\63\u0131\40\37\63\36\40\342\63";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\5\23\1\24\1\25\6\26"+
    "\1\27\1\30\1\31\1\1\1\31\1\32\1\33\4\0"+
    "\1\34\1\35\1\36\4\23\2\26\1\37\3\26\1\40"+
    "\1\41\3\23\1\42\6\26\1\43\1\44\1\23\1\45"+
    "\1\46\2\26\1\47\1\26\1\50\1\26\1\51\2\26"+
    "\1\52\1\53";

  private static int [] zzUnpackAction() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\160\0\250\0\340\0\160\0\u0118"+
    "\0\u0150\0\160\0\160\0\160\0\160\0\160\0\u0188\0\u01c0"+
    "\0\160\0\u01f8\0\u0230\0\160\0\160\0\u0268\0\160\0\u02a0"+
    "\0\u02d8\0\u0310\0\u0348\0\u0380\0\160\0\160\0\u03b8\0\u03f0"+
    "\0\u0428\0\u0460\0\u0498\0\u04d0\0\160\0\160\0\160\0\u0508"+
    "\0\u0540\0\160\0\160\0\u0578\0\u05b0\0\u05e8\0\u01c0\0\u01c0"+
    "\0\160\0\160\0\u0620\0\u0658\0\u0690\0\u06c8\0\u0700\0\u0738"+
    "\0\u03b8\0\u0770\0\u07a8\0\u07e0\0\160\0\160\0\u0818\0\u0850"+
    "\0\u0888\0\u02a0\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8"+
    "\0\u02a0\0\u02a0\0\u0a10\0\u03b8\0\u03b8\0\u0a48\0\u0a80\0\u03b8"+
    "\0\u0ab8\0\u02a0\0\u0af0\0\u03b8\0\u0b28\0\u0b60\0\u03b8\0\u03b8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\3\1\36\1\3"+
    "\3\37\1\40\1\41\2\37\1\42\3\37\1\43\1\44"+
    "\3\37\1\45\1\46\2\3\1\37\1\22\1\30\17\47"+
    "\1\50\41\47\1\51\1\3\5\47\72\0\1\4\113\0"+
    "\1\52\51\0\1\53\57\0\36\54\1\55\24\54\24\0"+
    "\1\56\1\57\1\0\1\22\43\0\1\22\23\0\1\60"+
    "\43\0\1\60\21\0\1\57\1\0\1\22\43\0\1\22"+
    "\24\0\1\61\72\0\1\62\63\0\1\30\5\0\5\30"+
    "\3\0\21\30\5\0\1\30\23\0\1\30\5\0\5\30"+
    "\3\0\13\30\1\63\5\30\5\0\1\30\23\0\1\30"+
    "\5\0\5\30\3\0\7\30\1\64\11\30\5\0\1\30"+
    "\23\0\1\30\5\0\5\30\3\0\11\30\1\65\7\30"+
    "\5\0\1\30\23\0\1\30\5\0\5\30\3\0\12\30"+
    "\1\66\6\30\5\0\1\30\23\0\1\37\5\0\5\37"+
    "\3\0\21\37\5\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\1\37\1\67\17\37\5\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\11\37\1\70\7\37\5\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\6\37\1\71\10\37"+
    "\1\72\1\37\5\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\15\37\1\73\3\37\5\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\5\37\1\74\13\37\5\0\1\37"+
    "\63\0\1\75\24\0\1\75\61\0\1\76\67\0\1\76"+
    "\24\0\1\54\3\0\1\54\7\0\1\54\2\0\1\54"+
    "\1\0\1\54\10\0\2\56\1\4\2\0\1\5\56\56"+
    "\1\0\3\56\22\0\1\30\5\0\5\30\3\0\13\30"+
    "\1\77\5\30\5\0\1\30\23\0\1\30\5\0\5\30"+
    "\3\0\1\30\1\100\17\30\5\0\1\30\23\0\1\30"+
    "\5\0\5\30\3\0\13\30\1\101\5\30\5\0\1\30"+
    "\23\0\1\30\5\0\5\30\3\0\17\30\1\102\1\30"+
    "\5\0\1\30\23\0\1\37\5\0\5\37\3\0\17\37"+
    "\1\103\1\37\5\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\16\37\1\104\2\37\5\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\5\37\1\105\13\37\5\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\10\37\1\106\10\37"+
    "\5\0\1\37\23\0\1\37\5\0\5\37\3\0\1\37"+
    "\1\107\15\37\1\110\1\37\5\0\1\37\23\0\1\30"+
    "\5\0\5\30\3\0\11\30\1\111\7\30\5\0\1\30"+
    "\23\0\1\30\5\0\5\30\3\0\15\30\1\112\3\30"+
    "\5\0\1\30\23\0\1\30\5\0\5\30\3\0\1\30"+
    "\1\113\17\30\5\0\1\30\23\0\1\37\5\0\5\37"+
    "\3\0\1\37\1\114\17\37\5\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\5\37\1\115\13\37\5\0\1\37"+
    "\23\0\1\37\5\0\5\37\3\0\15\37\1\116\3\37"+
    "\5\0\1\37\23\0\1\37\5\0\5\37\3\0\12\37"+
    "\1\117\6\37\5\0\1\37\23\0\1\37\5\0\5\37"+
    "\3\0\4\37\1\120\14\37\5\0\1\37\23\0\1\37"+
    "\5\0\5\37\3\0\20\37\1\121\5\0\1\37\23\0"+
    "\1\30\5\0\5\30\3\0\17\30\1\122\1\30\5\0"+
    "\1\30\23\0\1\37\5\0\5\37\3\0\1\37\1\123"+
    "\17\37\5\0\1\37\23\0\1\37\5\0\5\37\3\0"+
    "\17\37\1\124\1\37\5\0\1\37\23\0\1\37\5\0"+
    "\5\37\3\0\15\37\1\125\3\37\5\0\1\37\23\0"+
    "\1\37\5\0\5\37\3\0\17\37\1\126\1\37\5\0"+
    "\1\37\23\0\1\37\5\0\5\37\3\0\12\37\1\127"+
    "\6\37\5\0\1\37\23\0\1\37\5\0\5\37\3\0"+
    "\5\37\1\130\13\37\5\0\1\37\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2968];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\5\11\2\1\1\11"+
    "\2\1\2\11\1\1\1\11\5\1\2\11\6\1\3\11"+
    "\2\1\2\11\4\0\1\1\2\11\12\1\2\11\32\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[88];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    /* Código arbitrário pode ser inserido diretamente no analisador dessa forma. 
     * Aqui podemos declarar variáveis e métodos adicionais que julgarmos necessários. 
     */
    private int ntk;
    
    public int readedTokens(){
       return ntk;
    }
    private Token symbol(TOKEN_TYPE t) {
        ntk++;
        return new Token(t, yytext(), yyline+1, yycolumn+1);
        
    }
    private Token symbol(TOKEN_TYPE t, Object value) {
        ntk++;
        return new Token(t, value, yyline+1, yycolumn+1);
    }
    
    private void incTks() { ++ntk; }
    
    private int numTokens() { return ntk; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lext(java.io.Reader in) {
      ntk = 0; // Isto é copiado direto no construtor do lexer. 
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
          // fall through
          case 44: break;
          case 2:
            { 
            }
          // fall through
          case 45: break;
          case 3:
            { return symbol(TOKEN_TYPE.NOT);
            }
          // fall through
          case 46: break;
          case 4:
            { return symbol(TOKEN_TYPE.MOD);
            }
          // fall through
          case 47: break;
          case 5:
            { return symbol(TOKEN_TYPE.OPT);
            }
          // fall through
          case 48: break;
          case 6:
            { return symbol(TOKEN_TYPE.CPT);
            }
          // fall through
          case 49: break;
          case 7:
            { return symbol(TOKEN_TYPE.TIMES);
            }
          // fall through
          case 50: break;
          case 8:
            { return symbol(TOKEN_TYPE.PLUS);
            }
          // fall through
          case 51: break;
          case 9:
            { return symbol(TOKEN_TYPE.CMA);
            }
          // fall through
          case 52: break;
          case 10:
            { return symbol(TOKEN_TYPE.MINUS);
            }
          // fall through
          case 53: break;
          case 11:
            { return symbol(TOKEN_TYPE.DOT);
            }
          // fall through
          case 54: break;
          case 12:
            { return symbol(TOKEN_TYPE.DIV);
            }
          // fall through
          case 55: break;
          case 13:
            { System.out.print("INT: "); return symbol(TOKEN_TYPE.VAL_INT, Integer.parseInt(yytext()));
            }
          // fall through
          case 56: break;
          case 14:
            { return symbol(TOKEN_TYPE.DDOT);
            }
          // fall through
          case 57: break;
          case 15:
            { return symbol(TOKEN_TYPE.SEMI);
            }
          // fall through
          case 58: break;
          case 16:
            { return symbol(TOKEN_TYPE.LT);
            }
          // fall through
          case 59: break;
          case 17:
            { return symbol(TOKEN_TYPE.EQ);
            }
          // fall through
          case 60: break;
          case 18:
            { return symbol(TOKEN_TYPE.BT);
            }
          // fall through
          case 61: break;
          case 19:
            { return symbol(TOKEN_TYPE.TYPE);
            }
          // fall through
          case 62: break;
          case 20:
            { return symbol(TOKEN_TYPE.OCT);
            }
          // fall through
          case 63: break;
          case 21:
            { return symbol(TOKEN_TYPE.CCT);
            }
          // fall through
          case 64: break;
          case 22:
            { System.out.print("ID: "); return symbol(TOKEN_TYPE.ID);
            }
          // fall through
          case 65: break;
          case 23:
            { return symbol(TOKEN_TYPE.OCV);
            }
          // fall through
          case 66: break;
          case 24:
            { return symbol(TOKEN_TYPE.CCV);
            }
          // fall through
          case 67: break;
          case 25:
            { /* Ignora os caracteres dentro do bloco de comentário */
            }
          // fall through
          case 68: break;
          case 26:
            { return symbol(TOKEN_TYPE.NEQ);
            }
          // fall through
          case 69: break;
          case 27:
            { return symbol(TOKEN_TYPE.AND);
            }
          // fall through
          case 70: break;
          case 28:
            { System.out.print("FLOAT: "); return symbol(TOKEN_TYPE.VAL_FLOAT, Float.parseFloat(yytext()));
            }
          // fall through
          case 71: break;
          case 29:
            { return symbol(TOKEN_TYPE.DDDOT);
            }
          // fall through
          case 72: break;
          case 30:
            { return symbol(TOKEN_TYPE.EQEQ);
            }
          // fall through
          case 73: break;
          case 31:
            { return symbol(TOKEN_TYPE.IF);
            }
          // fall through
          case 74: break;
          case 32:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 75: break;
          case 33:
            { return symbol(TOKEN_TYPE.LITERAL_CARACTERE);
            }
          // fall through
          case 76: break;
          case 34:
            { return symbol(TOKEN_TYPE.INT);
            }
          // fall through
          case 77: break;
          case 35:
            { return symbol(TOKEN_TYPE.BOOL);
            }
          // fall through
          case 78: break;
          case 36:
            { return symbol(TOKEN_TYPE.CHAR);
            }
          // fall through
          case 79: break;
          case 37:
            { return symbol(TOKEN_TYPE.DATA);
            }
          // fall through
          case 80: break;
          case 38:
            { return symbol(TOKEN_TYPE.ELSE);
            }
          // fall through
          case 81: break;
          case 39:
            { return symbol(TOKEN_TYPE.READ);
            }
          // fall through
          case 82: break;
          case 40:
            { return symbol(TOKEN_TYPE.FLOAT);
            }
          // fall through
          case 83: break;
          case 41:
            { return symbol(TOKEN_TYPE.PRINT);
            }
          // fall through
          case 84: break;
          case 42:
            { return symbol(TOKEN_TYPE.RET);
            }
          // fall through
          case 85: break;
          case 43:
            { return symbol(TOKEN_TYPE.ITERATE);
            }
          // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
