package parsers;

import ast.*;
import java.io.IOException;
import beaver.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "MiniLang.grammar".
 */
public class MiniLangParser extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjbdcOJbKSnx$lVMaChsKM#pR6DXYCMPWPPcIRhA6La6Gg5D4cAY6bgD1cAKdqJy$JK$$" +
		"rb90A9QL5sYGXXIIKadJwt3ldlNFVyTB$vJxFztn$s$dTtptddaLo9kXYvQc7UYjBNPIl0X" +
		"MggxgPD#FRprl$1zOCSrgZLAHipT1qbQYJffiZQgMsobG7fIbP6RHDbAePvW3jM5KYihuVS" +
		"Rtgw5OrqqsQR7vKZiPfWiOIELhNQ8okrGNb$e2KeK6yDHfJJ1M7qQCvCrHA3Iq2#fM1cgOJ" +
		"$QSg1xorTM5CxzkL6D2ATOicHNLZw5dgUnVZluTl2iDLz9GSLTKZvZNVxsSnnucArfk1l49" +
		"BVEzOnkyANxDHvdTTxlTm$KC2MhQ7cUgi#zNJrulLNwjqgH8KqN9LHo$LqtfOrNIrQe2Qw2" +
		"EOeoBLeuQxuEQWDMW3sc5h1RS77P6Bb4k6lfwjk$hGlnPoATfmNQKac#a6C1xS2AQ0sy1Kt" +
		"SdyZ42wMmzgeKOmEmle$mGOfIVvThTlYPu7Ax6bgAuQgB4QWaPggdHp0gcbUkaYzTC0SWtK" +
		"O0tL9RhCh3UlQvX6wZhTh8cQfNjrXsPh6jfzcgC7uBcQf$dcc1xIergan$IusM$#rZDQPdx" +
		"JitAVfIf$dbE8MGlpLrRcNqjW5XEPmsgCO7pxUUj$t#hmNqHOY#tnP$AdTw9DPJtLO0NLOX" +
		"ViJ8JR5k9Fzjfy4F4Zqlbxc$0Vfx5R9REsshAstCZQx61rMNlXWBzSSiWGyMEIq5C3EHrMI" +
		"4gC7cRrHhLCh#PGm9l7QegD3WUq97Ab#BhRiu6lvUDFmTBDgwWxUsCBj5w#lpoBkqQYzJh8" +
		"8TPir1lonY#gHQEIEJkYikilZj5ST66qmzw8b#dkw1U0hbYBE3UIgBG7Uru7zYWNMUZPMDr" +
		"OXrqhsYyAXnhAvRACOMjp##SWD$2qBCOxcYaUilZUR2k5aLBy6Y9OGbvVTroJF5ioCRbaR0" +
		"roFItPaoBCIv8tDpdO8bQEy6KHRmGpuJ1Qs9k3TFJwdZN7c$tcx8#ktWXPNaQfmF2ebV4Vl" +
		"DBgcTxs5fe5ge9IgtS6Yy1iC0LC16dWOx0MP1Dau09m55INdFgsR#CoTjhGL4ElXzm0L06D" +
		"R4mwSfehszWicZhO#oCtAxCfofcMk#3V2$U43yE3uEFmC9ipWMOiF1UU5CqT3yJyG3CD7cf" +
		"pp#6zxQnl7ZY17lsE39e5S5FGCL1peJUASXWBfmE6PN1BwyiZnt2uBSeBo6EG6LCd$rnrsR" +
		"wzRKslq6y#l0OcjpR1A$7tWSUNnykTat5MteaycPXEo7nZYB5o2knthQCv1a#rxocXEGrt0" +
		"tr19XY8d$SuZBKp1BaGpW69e8VjrmzqnRSShWkwWs6W6Digk3OO34RQ#2B0l8PMmmF0Q91k" +
		"VUuSlWYdLfYV8VPx3WPiIoh4l1IGNxROQllj3VWw1#HNBP#qVDh6xpzp7a9hR8sErTTQNcz" +
		"vW#MDbZVRNBi3ERPONbmnVvptRGl8I#FP0xOLjhR42lQP0NdbMTwp0sp$jthYzDjfUPVbtR" +
		"Q6XXNYzWJaVG5vVr2tjaCLz8MnkjCy8BV2Vy3AQS4us$T879kxDnqxo$SiAPUTrW7xgTWuh" +
		"PPzp2cTup6iDtFGrxu1EprfbpdaMxy67u5ju4Fm0TWAtZUiOlCPs6BUC##QpMQJsMZUCMzx" +
		"lTxmshTiZkyj7pORp4zcRQ22TJ7r$6n#CKVDFhFNx37VcTtcMspi9MOx#1HyuaLzLPR1V1d" +
		"JzmlBdmVpL$ZU7MUn$nMZ$M7vLtCIAk6U8E3U5DoxGzdzmPMBF3YSsW8XRXILET4hSQ8BkE" +
		"Uc2qVkIU6Ue#nA8EJTgmgnixi2zuvLanCYaTCr34ASiMSY5ryU#VEupPLnsCBLAu4QzduHH" +
		"8WpFHm7ZaNe773Z4hZ728GyETCxhok1C2TRPVN#1n3z5nC=");
 private boolean good;
          
          public boolean isGood(){ return good;}
          
          protected void recoverFromError(Symbol token, TokenStream in) throws IOException, Parser.Exception{
              super.recoverFromError(token, in);
              good = false;
          }

	private final Action[] actions;

	public MiniLangParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			Action.NONE,  	// [0] opt$Data = 
			Action.RETURN,	// [1] opt$Data = Data
			new Action() {	// [2] Def = opt$Data.d
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_d = _symbols[offset + 1];
					final Node d = (Node) _symbol_d.value;
					 return d;
				}
			},
			new Action() {	// [3] lst$Func = Func
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [4] lst$Func = lst$Func Func
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [5] Def = lst$Func.fn
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_fn = _symbols[offset + 1];
					final ArrayList _list_fn = (ArrayList) _symbol_fn.value;
					final Node[] fn = _list_fn == null ? new Node[0] : (Node[]) _list_fn.toArray(new Node[_list_fn.size()]);
					 return fn;
				}
			},
			new Action() {	// [6] lst$Decl = Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [7] lst$Decl = lst$Decl Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [8] opt$lst$Decl = 
			Action.RETURN,	// [9] opt$lst$Decl = lst$Decl
			new Action() {	// [10] Data = TYPE_DATA NAME.nm OPEN_BRACE opt$lst$Decl.dl CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_nm = _symbols[offset + 2];
					final String nm = (String) _symbol_nm.value;
					final Symbol _symbol_dl = _symbols[offset + 4];
					final ArrayList _list_dl = (ArrayList) _symbol_dl.value;
					final Node[] dl = _list_dl == null ? new Node[0] : (Node[]) _list_dl.toArray(new Node[_list_dl.size()]);
					 return new Data(nm, dl);
				}
			},
			new Action() {	// [11] Decl = ID.v SRO Type.t SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					 return new Decl(v, t);
				}
			},
			Action.NONE,  	// [12] opt$Param = 
			Action.RETURN,	// [13] opt$Param = Param
			new Action() {	// [14] lst$FP = FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [15] lst$FP = lst$FP FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [16] opt$lst$FP = 
			Action.RETURN,	// [17] opt$lst$FP = lst$FP
			Action.NONE,  	// [18] opt$FP = 
			Action.RETURN,	// [19] opt$FP = FP
			new Action() {	// [20] lst$Cmd = Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [21] lst$Cmd = lst$Cmd Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [22] opt$lst$Cmd = 
			Action.RETURN,	// [23] opt$lst$Cmd = lst$Cmd
			new Action() {	// [24] Func = ID.v AP opt$Param.p FP AP COLON Type.t AP COMMA Type.t opt$lst$FP opt$FP OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final Node p = (Node) _symbol_p.value;
					final Symbol _symbol_t = _symbols[offset + 7];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_t = _symbols[offset + 10];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_c = _symbols[offset + 14];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return new Func(v, p, t, c);
				}
			},
			new Action() {	// [25] Param = ID.v SRO Type.t AP COMMA ID.v SRO Type.t opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_v = _symbols[offset + 6];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 8];
					final Node t = (Node) _symbol_t.value;
					 return new Param(v, t, v, t);
				}
			},
			new Action() {	// [26] Type = Type.t OPEN_BRACKET CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final Node t = (Node) _symbol_t.value;
					 return new TyArr(t);
				}
			},
			new Action() {	// [27] Type = Btype.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_b = _symbols[offset + 1];
					final Node b = (Node) _symbol_b.value;
					 return b;
				}
			},
			new Action() {	// [28] Btype = TYPE_INT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyInt();
				}
			},
			new Action() {	// [29] Btype = TYPE_CHAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyChar();
				}
			},
			new Action() {	// [30] Btype = TYPE_BOOL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyBool();
				}
			},
			new Action() {	// [31] Btype = TYPE_FLOAT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyFloat();
				}
			},
			new Action() {	// [32] Btype = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new CustomType(v);
				}
			},
			new Action() {	// [33] Block = OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 2];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return c;
				}
			},
			new Action() {	// [34] Cmd = IF AP Exp.e FP Block.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_b = _symbols[offset + 5];
					final Node b = (Node) _symbol_b.value;
					 return new If(e, b);
				}
			},
			new Action() {	// [35] Cmd = IF AP Exp.e FP Block.b1 ELSE Block.b2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_b1 = _symbols[offset + 5];
					final Node b1 = (Node) _symbol_b1.value;
					final Symbol _symbol_b2 = _symbols[offset + 7];
					final Node b2 = (Node) _symbol_b2.value;
					 return new If(e,b1,b2);
				}
			},
			new Action() {	// [36] Cmd = ITERATE AP Exp.e FP Block.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_b = _symbols[offset + 5];
					final Node b = (Node) _symbol_b.value;
					 return new While(e, b);
				}
			},
			new Action() {	// [37] Cmd = READ Lvalue.l SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 2];
					final Node l = (Node) _symbol_l.value;
					 return new Read(l);
				}
			},
			new Action() {	// [38] Cmd = PRINT Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Print(e);
				}
			},
			new Action() {	// [39] Cmd = RETURN Exp.e AP COMMA Exp opt$lst$FP SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Return(e);
				}
			},
			new Action() {	// [40] Cmd = Lvalue.l EQUAL Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Equal(l, e);
				}
			},
			new Action() {	// [41] Cmd = ID.fn AP Exps FP AP LESS_THAN Lvalue AP COMMA Lvalue opt$lst$FP GREATER_THAN opt$FP SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_fn = _symbols[offset + 1];
					final String fn = (String) _symbol_fn.value;
					 return new Call(fn, e, l);
				}
			},
			new Action() {	// [42] CExpr = Exp.e1 AND Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new And(e1,e2);
				}
			},
			new Action() {	// [43] CExpr = Exp.e1 LESS_THAN Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Lt(e1,e2);
				}
			},
			new Action() {	// [44] CExpr = Exp.e1 EQUAL_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new EqEq(e1,e2);
				}
			},
			new Action() {	// [45] CExpr = Exp.e1 NO_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new NotEqual(e1, e2);
				}
			},
			new Action() {	// [46] CExpr = Exp.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					 return e;
				}
			},
			new Action() {	// [47] Exp = Exp.e1 PLUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Add(e1, e2);
				}
			},
			new Action() {	// [48] Exp = Exp.e1 MINUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Sub(e1, e2);
				}
			},
			new Action() {	// [49] Exp = Exp.e1 MULT Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mul(e1, e2);
				}
			},
			new Action() {	// [50] Exp = Exp.e1 DIV Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Div(e1, e2);
				}
			},
			new Action() {	// [51] Exp = Exp.e1 MOD Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mod(e1, e2);
				}
			},
			new Action() {	// [52] Exp = NOT CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Not((Expr) e);
				}
			},
			new Action() {	// [53] Exp = MINUS CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Neg((Expr) e);
				}
			},
			new Action() {	// [54] Exp = INT.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Integer n = (Integer) _symbol_n.value;
					 return new NInt(n);
				}
			},
			new Action() {	// [55] Exp = FLOAT.f
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_f = _symbols[offset + 1];
					final Float f = (Float) _symbol_f.value;
					 return new NFloat(f);
				}
			},
			new Action() {	// [56] Exp = CHAR.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 1];
					final Character c = (Character) _symbol_c.value;
					 return new NChar(c);
				}
			},
			new Action() {	// [57] Exp = TRUE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new True();
				}
			},
			new Action() {	// [58] Exp = FALSE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new False();
				}
			},
			new Action() {	// [59] Exp = NULL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new Null();
				}
			},
			new Action() {	// [60] Exp = Lvalue.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					 return l;
				}
			},
			new Action() {	// [61] Exp = AP CExpr.e FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return e;
				}
			},
			new Action() {	// [62] Exp = TYPE_NEW Type.t AP OPEN_BRACKET CExpr.e CLOSE_BRACKET opt$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 2];
					final Node t = (Node) _symbol_t.value;
					final Symbol e = _symbols[offset + 5];
					 return e;
				}
			},
			Action.NONE,  	// [63] opt$Exps = 
			Action.RETURN,	// [64] opt$Exps = Exps
			new Action() {	// [65] Exp = ID.v AP opt$Exps.e FP OPEN_BRACKET CExpr.ce CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Node e = (Node) _symbol_e.value;
					final Symbol ce = _symbols[offset + 6];
					 return new Call(v, ce, e);
				}
			},
			new Action() {	// [66] Lvalue = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new Var(v);
				}
			},
			new Action() {	// [67] Lvalue = Lvalue.l OPEN_BRACKET Exp.e CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Index(l, e);
				}
			},
			new Action() {	// [68] Lvalue = Lvalue.l DOT ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_v = _symbols[offset + 3];
					final String v = (String) _symbol_v.value;
					 return new Field(l, v);
				}
			},
			new Action() {	// [69] Exps = Exp.e AP COMMA Exp.ep opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_ep = _symbols[offset + 4];
					final Expr ep = (Expr) _symbol_ep.value;
					 return new ExpList(e, ep);
				}
			}
		};

 good = true;
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
