package parsers;

import ast.*;
import java.io.IOException;
import beaver.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "MiniLang.grammar".
 */
public class MiniLangParser extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjbbbm55KKXl$k2S7819W4GmGa2H2sC9EmX01X7HSMHKN5YHikg8WAuYuQ41N57GNbGHy" +
		"jgxIKAYqVB0iLSM5H4KL450GH1K54516KvVfrvywaPpAaVBRehh$$S$vpxjhtzct9dQXhT8" +
		"ukrcKQfmawJ#Vh0atKXURzxFfnzN#bnbLlZgY3dbKttQ8SjL2zN8tKQJf3OzJIB56nAimkL" +
		"MeEMGDLgrduEts$tledwd7bQhnkrvsQYTfE9wb8xSsVgPB9p5mDLoTLu7lgOrRDLnkqGb#h" +
		"IxP1ppp$jWRV75J4xCLBzYokKfr0cH1gtEztMFq2qS41Upej93GjfIJKDn0jnZzBSND0KtI" +
		"cxj6DWLOQi#udRnvyhtednzSaQvvVMt$uKQpg9dd5QQssPYxYYgIosZQfhouLUrYdfEnvtC" +
		"CLuqvea8RfPFLG7vMf5tShTLKUirBdZyb3WSwbZKjI$jMwalBNq$8GimTb11W5JWMdqt92e" +
		"uabDDP$dgr9kfpw4ff1x6PMY9Tn1xWBt4tD2Sq6zu6vUf1uGe$eISsdp4BciL3Fe7KahxDA" +
		"r4NbwexTKrMAgaO3M0T3TP4krHMwYfvDrhMwJZVe9hDCKytRkjNiqnDwG4$f8Jsj1MQ77DP" +
		"co7$RkMh9#yzZxRNYpMVNZwl$9zL55wXcz$PZvG$6hcLdj#RhqPQlroZy0bQSjqySzaanEo" +
		"FJByJgmdxfoLxfZTs1jTc9lHLkajc5TJe4rV7L4LPrMBS5V9SyhIpLXklxuLGR4RHmgcUkB" +
		"LFDxdNzVWzCYmRj42rKi9kJIj1sRSobXM7ie1BsOcFPp3fSMekbnfUPLU7N5eEzFZNDSz9Q" +
		"BML4BaXc5JMfhomLwqwVadO5TyJ$KddzBcBS0xX3xFmQzdsKhrWb9RsOXnB65059F#pRLNx" +
		"$2b9g4lbsBXgVKMgkj35lXUIdvKVIF2$UM2PAMvM#5Y8ln3UqCr$n0cpE5n$b$fmwv4NePv" +
		"XeY6S9UPuIzkzIlCwCqfklC2jrqHnvbrFeBLhFJe9h9zeuC0BasxmPbfy7hS5Ywwy9biq6o" +
		"OsILmgMOrU2jjYpmHRi8dW1Y8DT#DqeS1Gkj$NdMkw8rYDGvq0UhT3hG7Vyzd2LZGtYuTKx" +
		"2Goosb3ibNPyPTXJu3xMhx7izU4WF9xyN9YwtJnuieqV1jF9UG6UsVoOdNBA3hVbvc8FiFg" +
		"BsCo$MuKp7#uAQWBZYXikU0WOZF0StDF6Xb5#6jmRXtgSUcpUaJkoiRnUGty9NWA$2JFdpf" +
		"90$0lyETRUXEtreI$s3konsBMsdw$m#0DUQDiU1MBuRy3UVFS34q1$jBTWtgyx9j3EQlHUn" +
		"vYRbmDsD62tQsvEizUb8nbrnm8s$T9Q#kLQ$zL0RAhbnLdwDzxoJCkp0h7NBQ#syr8OYAsr" +
		"lCxoUiiRB6#qlDdon43PhPQN$lUnEyioorjxXUrR92D$TC1UTOmwjuDjMVJTblTOtfiHtnU" +
		"mzmVi0y6OrGvbgJ#RndV0ETBeQr43cQFci3aaUvc$mD$MtW#scv$CZsQR#S5iDT#RVzJCPN" +
		"u6l$ZM5hCxfMu6twMyJVvpe$LOJuOzP3u7Qy1dOBNvakVNu5FpYVdOh38hpGgpt7o4yevVw" +
		"iD0ctlC1#PNipIWl9VMfz$CxuQTPzQ3hy0wysv3jlasBUyRonkoZenl2F$fjVvVYEl$VLHR" +
		"3FNXShu9E9pvBJZxSlYV470uPpouyhuAVR7PuS3XLFJWSaOAEFmfjE7F8yy$fQBubLaG8nQ" +
		"Z$XX$IWqSil3y7CxFK0OSphrG5hWMJZFmybhozo7W#7Q5VpBcW13$8oqK$nSwXmK0");
 private boolean good;
          
          public boolean isGood(){ return good;}
          
          protected void recoverFromError(Symbol token, TokenStream in) throws IOException, Parser.Exception{
              super.recoverFromError(token, in);
              good = false;
          }

	private final Action[] actions;

	public MiniLangParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] lst$Def = Def
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [1] lst$Def = lst$Def Def
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [2] Prog = lst$Def.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final ArrayList _list_s = (ArrayList) _symbol_s.value;
					final Node[] s = _list_s == null ? new Node[0] : (Node[]) _list_s.toArray(new Node[_list_s.size()]);
					 return new Program(s);
				}
			},
			new Action() {	// [3] Def = Data.d
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_d = _symbols[offset + 1];
					final Node d = (Node) _symbol_d.value;
					 return d;
				}
			},
			new Action() {	// [4] Def = Func.fn
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_fn = _symbols[offset + 1];
					final Node fn = (Node) _symbol_fn.value;
					 return fn;
				}
			},
			new Action() {	// [5] lst$Decl = Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [6] lst$Decl = lst$Decl Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [7] opt$lst$Decl = 
			Action.RETURN,	// [8] opt$lst$Decl = lst$Decl
			new Action() {	// [9] Data = TYPE_DATA NAME.nm OPEN_BRACE opt$lst$Decl.dl CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_nm = _symbols[offset + 2];
					final String nm = (String) _symbol_nm.value;
					final Symbol _symbol_dl = _symbols[offset + 4];
					final ArrayList _list_dl = (ArrayList) _symbol_dl.value;
					final Node[] dl = _list_dl == null ? new Node[0] : (Node[]) _list_dl.toArray(new Node[_list_dl.size()]);
					 return new Data(nm, dl);
				}
			},
			new Action() {	// [10] Decl = ID.v SRO Type.t SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					 return new Decl(v, t);
				}
			},
			Action.NONE,  	// [11] opt$Params = 
			Action.RETURN,	// [12] opt$Params = Params
			new Action() {	// [13] lst$FP = FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [14] lst$FP = lst$FP FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [15] opt$lst$FP = 
			Action.RETURN,	// [16] opt$lst$FP = lst$FP
			Action.NONE,  	// [17] opt$FP = 
			Action.RETURN,	// [18] opt$FP = FP
			new Action() {	// [19] lst$Cmd = Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [20] lst$Cmd = lst$Cmd Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [21] opt$lst$Cmd = 
			Action.RETURN,	// [22] opt$lst$Cmd = lst$Cmd
			new Action() {	// [23] Func = ID.v AP opt$Params.p FP AP COLON Type.t AP COMMA Type.t opt$lst$FP opt$FP OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final Node p = (Node) _symbol_p.value;
					final Symbol _symbol_t = _symbols[offset + 7];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_t = _symbols[offset + 10];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_c = _symbols[offset + 14];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return new Func(v, p, t, c);
				}
			},
			new Action() {	// [24] Params = ID.v SRO Type.t AP COMMA ID.v SRO Type.t opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_v = _symbols[offset + 6];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 8];
					final Node t = (Node) _symbol_t.value;
					 return new Params(v, t, v, t);
				}
			},
			new Action() {	// [25] Type = Type.t OPEN_BRACKET CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final Node t = (Node) _symbol_t.value;
					 return new ArrayType(t);
				}
			},
			new Action() {	// [26] Type = Btype.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_b = _symbols[offset + 1];
					final Node b = (Node) _symbol_b.value;
					 return b;
				}
			},
			new Action() {	// [27] Btype = TYPE_INT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyInt();
				}
			},
			new Action() {	// [28] Btype = TYPE_CHAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyChar();
				}
			},
			new Action() {	// [29] Btype = TYPE_BOOL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyBool();
				}
			},
			new Action() {	// [30] Btype = TYPE_FLOAT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyFloat();
				}
			},
			new Action() {	// [31] Btype = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new CustomType(v);
				}
			},
			new Action() {	// [32] Cmd = OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 2];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return new Block(c);
				}
			},
			new Action() {	// [33] Cmd = IF AP Exp.e FP Cmd.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Node c = (Node) _symbol_c.value;
					 return new If(e, c);
				}
			},
			new Action() {	// [34] Cmd = IF AP Exp.e FP Cmd.c1 ELSE Cmd.c2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c1 = _symbols[offset + 5];
					final Node c1 = (Node) _symbol_c1.value;
					final Symbol _symbol_c2 = _symbols[offset + 7];
					final Node c2 = (Node) _symbol_c2.value;
					 return new If(e,c1,c2);
				}
			},
			new Action() {	// [35] Cmd = ITERATE AP Exp.e FP Cmd.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Node c = (Node) _symbol_c.value;
					 return new While(e, c);
				}
			},
			new Action() {	// [36] Cmd = READ Lvalue.l SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 2];
					final Node l = (Node) _symbol_l.value;
					 return new Read(l);
				}
			},
			new Action() {	// [37] Cmd = PRINT Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Print(e);
				}
			},
			new Action() {	// [38] Cmd = RETURN Exp.e AP COMMA Exp opt$lst$FP SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Return(e);
				}
			},
			new Action() {	// [39] Cmd = Lvalue.l EQUAL Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Equal(l, e);
				}
			},
			new Action() {	// [40] CExpr = Exp.e1 AND Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new And(e1,e2);
				}
			},
			new Action() {	// [41] CExpr = Exp.e1 LESS_THAN Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Lt(e1,e2);
				}
			},
			new Action() {	// [42] CExpr = Exp.e1 EQUAL_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new EqEq(e1,e2);
				}
			},
			new Action() {	// [43] CExpr = Exp.e1 NO_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new NotEqual(e1, e2);
				}
			},
			new Action() {	// [44] CExpr = Exp.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					 return e;
				}
			},
			new Action() {	// [45] Exp = Exp.e1 PLUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Add(e1, e2);
				}
			},
			new Action() {	// [46] Exp = Exp.e1 MINUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Sub(e1, e2);
				}
			},
			new Action() {	// [47] Exp = Exp.e1 MULT Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mul(e1, e2);
				}
			},
			new Action() {	// [48] Exp = Exp.e1 DIV Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Div(e1, e2);
				}
			},
			new Action() {	// [49] Exp = Exp.e1 MOD Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mod(e1, e2);
				}
			},
			new Action() {	// [50] Exp = NOT CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Not((Expr) e);
				}
			},
			new Action() {	// [51] Exp = MINUS CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Neg((Expr) e);
				}
			},
			new Action() {	// [52] Exp = INT.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Integer n = (Integer) _symbol_n.value;
					 return new NInt(n);
				}
			},
			new Action() {	// [53] Exp = FLOAT.f
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_f = _symbols[offset + 1];
					final Float f = (Float) _symbol_f.value;
					 return new NFloat(f);
				}
			},
			new Action() {	// [54] Exp = CHAR.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 1];
					final Character c = (Character) _symbol_c.value;
					 return new NChar(c);
				}
			},
			new Action() {	// [55] Exp = TRUE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new True();
				}
			},
			new Action() {	// [56] Exp = FALSE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new False();
				}
			},
			new Action() {	// [57] Exp = NULL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new Null();
				}
			},
			new Action() {	// [58] Exp = Lvalue.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					 return l;
				}
			},
			new Action() {	// [59] Exp = AP CExpr.e FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return e;
				}
			},
			new Action() {	// [60] Exp = TYPE_NEW Type.t AP OPEN_BRACKET CExpr.e CLOSE_BRACKET opt$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 2];
					final Node t = (Node) _symbol_t.value;
					final Symbol e = _symbols[offset + 5];
					 return e;
				}
			},
			Action.NONE,  	// [61] opt$Exps = 
			Action.RETURN,	// [62] opt$Exps = Exps
			new Action() {	// [63] Exp = ID.v AP opt$Exps.e FP OPEN_BRACKET CExpr.ce CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Node e = (Node) _symbol_e.value;
					final Symbol ce = _symbols[offset + 6];
					 return new Call(v, e, ce);
				}
			},
			new Action() {	// [64] Lvalue = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new Var(v);
				}
			},
			new Action() {	// [65] Lvalue = Lvalue.l OPEN_BRACKET Exp.e CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Index(l, e);
				}
			},
			new Action() {	// [66] Lvalue = Lvalue.l DOT ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_v = _symbols[offset + 3];
					final String v = (String) _symbol_v.value;
					 return new Field(l, v);
				}
			},
			new Action() {	// [67] Exps = Exp.e AP COMMA Exp.ep opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_ep = _symbols[offset + 4];
					final Expr ep = (Expr) _symbol_ep.value;
					 return new ExpList(e, ep);
				}
			}
		};

 good = true;
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
