package parsers;

import ast.*;
import java.io.IOException;
import beaver.*;
import java.util.ArrayList;

/**
 * This class is a LALR parser generated by
 * <a href="http://beaver.sourceforge.net">Beaver</a> v0.9.6.1
 * from the grammar specification "MiniLang.grammar".
 */
public class MiniLangParser extends Parser {

	static final ParsingTables PARSING_TABLES = new ParsingTables(
		"U9pjbtcKrbCOnx$lRzhDl9cbCUqpxOkcMTIKD4sJ59NI8jCgMnHbAoIKIdPPieVASOv$EFt" +
		"X72U4K9Rif12LiaH9HQHSdtj$TzxvpNYBlp7l#TxdURxtkSzpzzyTAPYhoJfDupHHfsY4Hc" +
		"gKJjTedQ6wvkN3rFpF$llPMxHSRNIvQgcs5YfGO#N3fPcLggUZr5xrrLbDrD7iWEsgEUgkN" +
		"he6he5ApNVcrmZN6xPSj#2P6c77g4mLcguJTP86AaLryBAvfbMBjr3fki1cDhirKqFLLCSg" +
		"ZcU6EkeANLKjSxdINCGghbnbjBlDvsXEX9PaBJVxFTCGfboP#9IfI2qyIolrLDk4LQ5JOT8" +
		"rA5BVJ4Txwm7iYs5orCepLpkF75tdxHpbwdgOJBNpJ0Vbc4FCtitAKYDbwnYpI#UHeRpILb" +
		"v2exz42DjLSc7yBfwr$Qi3CqG5dZbEfVmglMSwZmeLQdY2AtNS67xZdLRA79pjj1jrbox4I" +
		"jU3rBPc1MRIyqx8XTZ5wcRsuTS3gq9zT3nbNz0Fz7TpDS2L9xjoc2RGhpCP6wDdZ7OMpz5W" +
		"NGHAD0cFItKPUwn2LsesN8LcWMl1N31V2rpTJLgCV9YsI#d92M2mbcWPt5YTHUnpTRwcw19" +
		"DDI#PvpH3ytI3RjKTkfsOYtGdvTswH$VgFhDNz#jHyutitoEkVCYLZod63azn#w#EwhB3wx" +
		"EFZsAFfHscvd$sly3sv2HrOyVrvWQoUxqGBiOPos0dbx33Cx1wSQ9YdAWSRiWct4yPs77GA" +
		"C9bmmPuDI965Pl7VPZFRTMGkoITNEtnihbwL8kNJxI#BdC6Exyj$IpXNixWjkd5NTYbMcQR" +
		"mqQiuW9of14np956X0um0Jq9cGAOW5ETxVooF1kswfwmRCnK#b4KgI#bJMZrmyw2YN7FXKm" +
		"hvn5BUCJ8OpsAwMF8s3cJysZ6lTo2UzcEBawxIZiheQMwSONjAhamVkKeRF$QmnGnEo7JYL" +
		"ZnX7Ucyx0eId1nP#VnAt9QdDivr3gJkuZnnycGHy$pQL$C2kJpoqCMKXV6isLX8hP5y9SoZ" +
		"NxPMKxrinndTbexf937UjWzPcKCBXehMcTb0MqBY98FMjFMSZ6uJ5OgXJovw6bkZNF9PAFR" +
		"swij$dPbyXbVTvXih3J3dt9TsIOiMOt7vxZBCDOKhBHw9N3O2bSRP85qxtUsbyLWAPZlxP9" +
		"essJ0PxWKD42U1wQ38U19y0oO1vu2PU1fi0pK1yjzsqmlMu0raPXRA5AHCq0XM0LE2kk24e" +
		"fZi6U3OPxhYzuur5aFnHOWktYxXvVzyAEExwA2jiWAP0VaESXkoEa#TrUAMSZLo0L$C$RlQ" +
		"JlMnr#4dklvPz7RWw7XTobWheD1LUs2yMwb58m4eo2UG6Rxkj6qlnLPZh42VHBw6M14LNiz" +
		"3$ysSYroVOJ$07knrpUXBw7T0FHlqQUW3$Vz#unYB$89dvErqn$82U1qC11CfHwVO1YOXlu" +
		"vSZ1e3YRwTfC1ynXx5zaVZ06iMJ0ERYCuY3wbHl$g9PzBROZe1o9pFFX8Qt2OTHbRmvuJqJ" +
		"VPNCYHFjVMIDrcBricYVcgbzkyt1wfs#7b3tvUEaJgTdgvsyizNkxpSh#N1xoSvEMAI8n3N" +
		"gx#9#FtlkiYkedex$i#TgpX7u$ewwDrLNmGjsSz2P$XPNODFYUYDudepQ9rdikjqP#I6lLb" +
		"4TsUvMPUxvsaFwsISDoBGRigMu#7mlnX3fhVvV$CB#0th$yClZRRpJRpbTbgjfZDve2Ey6S" +
		"uPUPxftrfVaYmNu1D2UjpLtxchVV1Uu3pOzu1d6cp3gmtd1JpCNZBl6dUCA#RjMQDUSsy2l" +
		"EyQ$bA9EykizhiDAiYp8lL#lMZ#SdiGNu4FZGlX9xcqse#6xtS48rJOtoV96Mvn$X$eG$Ve" +
		"Zvy9qzqRwqGPGw1x4rMZdu2hxBZUPkLOfTYTtC8#Fe9nFYc2TXtc4KWUzENeFVc9T2Fbrm1" +
		"Ny82xE8aAAIkaFY5lFf2cU9XxLeWxjuKrH7ZUvoI1857x0YmVdLvpmd4d9xltcorG0hljDh" +
		"g$oSBJqH2");
 private boolean good;
          
          public boolean isGood(){ return good;}
          
          protected void recoverFromError(Symbol token, TokenStream in) throws IOException, Parser.Exception{
              super.recoverFromError(token, in);
              good = false;
          }

	private final Action[] actions;

	public MiniLangParser() {
		super(PARSING_TABLES);
		actions = new Action[] {
			new Action() {	// [0] lst$Def = Def
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [1] lst$Def = lst$Def Def
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			new Action() {	// [2] Prog = lst$Def.s
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_s = _symbols[offset + 1];
					final ArrayList _list_s = (ArrayList) _symbol_s.value;
					final Node[] s = _list_s == null ? new Node[0] : (Node[]) _list_s.toArray(new Node[_list_s.size()]);
					 return new Program(s);
				}
			},
			new Action() {	// [3] Def = Data.d
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_d = _symbols[offset + 1];
					final Node d = (Node) _symbol_d.value;
					 return d;
				}
			},
			new Action() {	// [4] Def = Func.fn
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_fn = _symbols[offset + 1];
					final Node fn = (Node) _symbol_fn.value;
					 return fn;
				}
			},
			new Action() {	// [5] lst$Decl = Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [6] lst$Decl = lst$Decl Decl
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [7] opt$lst$Decl = 
			Action.RETURN,	// [8] opt$lst$Decl = lst$Decl
			new Action() {	// [9] Data = TYPE_DATA NAME.nm OPEN_BRACE opt$lst$Decl.dl CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_nm = _symbols[offset + 2];
					final String nm = (String) _symbol_nm.value;
					final Symbol _symbol_dl = _symbols[offset + 4];
					final ArrayList _list_dl = (ArrayList) _symbol_dl.value;
					final Node[] dl = _list_dl == null ? new Node[0] : (Node[]) _list_dl.toArray(new Node[_list_dl.size()]);
					 return new Data(nm, dl);
				}
			},
			new Action() {	// [10] Decl = ID.v SRO Type.t SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					 return new Decl(v, t);
				}
			},
			Action.NONE,  	// [11] opt$Params = 
			Action.RETURN,	// [12] opt$Params = Params
			new Action() {	// [13] lst$FP = FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [14] lst$FP = lst$FP FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [15] opt$lst$FP = 
			Action.RETURN,	// [16] opt$lst$FP = lst$FP
			Action.NONE,  	// [17] opt$FP = 
			Action.RETURN,	// [18] opt$FP = FP
			new Action() {	// [19] lst$Cmd = Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					ArrayList lst = new ArrayList(); lst.add(_symbols[offset + 1].value); return new Symbol(lst);
				}
			},
			new Action() {	// [20] lst$Cmd = lst$Cmd Cmd
				public Symbol reduce(Symbol[] _symbols, int offset) {
					((ArrayList) _symbols[offset + 1].value).add(_symbols[offset + 2].value); return _symbols[offset + 1];
				}
			},
			Action.NONE,  	// [21] opt$lst$Cmd = 
			Action.RETURN,	// [22] opt$lst$Cmd = lst$Cmd
			new Action() {	// [23] Func = ID.v OPEN_PARENTHESIS opt$Params.p CLOSE_PARENTHESIS AP COLON Type.t AP COMMA Type.t opt$lst$FP opt$FP OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_p = _symbols[offset + 3];
					final Node p = (Node) _symbol_p.value;
					final Symbol _symbol_t = _symbols[offset + 7];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_t = _symbols[offset + 10];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_c = _symbols[offset + 14];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return new Func(v, p, t, c);
				}
			},
			new Action() {	// [24] Params = ID.v SRO Type.t AP COMMA ID.v SRO Type.t opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 3];
					final Node t = (Node) _symbol_t.value;
					final Symbol _symbol_v = _symbols[offset + 6];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_t = _symbols[offset + 8];
					final Node t = (Node) _symbol_t.value;
					 return new Params(v, t, v, t);
				}
			},
			new Action() {	// [25] Type = Type.t OPEN_BRACKET CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 1];
					final Node t = (Node) _symbol_t.value;
					 return new ArrayType(t);
				}
			},
			new Action() {	// [26] Type = Btype.b
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_b = _symbols[offset + 1];
					final Node b = (Node) _symbol_b.value;
					 return b;
				}
			},
			new Action() {	// [27] Btype = TYPE_INT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyInt();
				}
			},
			new Action() {	// [28] Btype = TYPE_CHAR
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyChar();
				}
			},
			new Action() {	// [29] Btype = TYPE_BOOL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyBool();
				}
			},
			new Action() {	// [30] Btype = TYPE_FLOAT
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new TyFloat();
				}
			},
			new Action() {	// [31] Btype = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new CustomType(v);
				}
			},
			new Action() {	// [32] Cmd = OPEN_BRACE opt$lst$Cmd.c CLOSE_BRACE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 2];
					final ArrayList _list_c = (ArrayList) _symbol_c.value;
					final Node[] c = _list_c == null ? new Node[0] : (Node[]) _list_c.toArray(new Node[_list_c.size()]);
					 return new Block(c);
				}
			},
			new Action() {	// [33] Cmd = IF OPEN_PARENTHESIS Exp.e CLOSE_PARENTHESIS Cmd.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Node c = (Node) _symbol_c.value;
					 return new If(e, c);
				}
			},
			new Action() {	// [34] Cmd = IF OPEN_PARENTHESIS Exp.e CLOSE_PARENTHESIS Cmd.c1 ELSE Cmd.c2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c1 = _symbols[offset + 5];
					final Node c1 = (Node) _symbol_c1.value;
					final Symbol _symbol_c2 = _symbols[offset + 7];
					final Node c2 = (Node) _symbol_c2.value;
					 return new If(e,c1,c2);
				}
			},
			new Action() {	// [35] Cmd = ITERATE OPEN_PARENTHESIS Exp.e CLOSE_PARENTHESIS Cmd.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_c = _symbols[offset + 5];
					final Node c = (Node) _symbol_c.value;
					 return new While(e, c);
				}
			},
			new Action() {	// [36] Cmd = READ Lvalue.l SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 2];
					final Node l = (Node) _symbol_l.value;
					 return new Read(l);
				}
			},
			new Action() {	// [37] Cmd = PRINT Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Print(e);
				}
			},
			new Action() {	// [38] Cmd = RETURN Exp.e AP COMMA Exp opt$lst$FP SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 2];
					final Expr e = (Expr) _symbol_e.value;
					 return new Return(e);
				}
			},
			new Action() {	// [39] Cmd = Lvalue.l EQUAL Exp.e SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Equal(l, e);
				}
			},
			new Action() {	// [40] Cmd = ID OPEN_PARENTHESIS Exps CLOSE_PARENTHESIS AP LESS_THAN Lvalue AP COMMA Lvalue opt$lst$FP GREATER_THAN opt$FP SEMI
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new Call(fn, e, l);
				}
			},
			new Action() {	// [41] CExpr = CExpr.e1 AND CExpr.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e1 = _symbols[offset + 1];
					final Symbol e2 = _symbols[offset + 3];
					 return new And(e1,e2);
				}
			},
			new Action() {	// [42] CExpr = Exp.e1 LESS_THAN Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Lt(e1,e2);
				}
			},
			new Action() {	// [43] CExpr = Exp.e1 EQUAL_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new EqEq(e1,e2);
				}
			},
			new Action() {	// [44] CExpr = Exp.e1 NO_EQUAL Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Neq(e1, e2);
				}
			},
			new Action() {	// [45] CExpr = Exp.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					 return e;
				}
			},
			new Action() {	// [46] Exp = Exp.e1 PLUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Add(e1, e2);
				}
			},
			new Action() {	// [47] Exp = Exp.e1 MINUS Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Sub(e1, e2);
				}
			},
			new Action() {	// [48] Exp = Exp.e1 MULT Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mul(e1, e2);
				}
			},
			new Action() {	// [49] Exp = Exp.e1 DIV Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Div(e1, e2);
				}
			},
			new Action() {	// [50] Exp = Exp.e1 MOD Exp.e2
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e1 = _symbols[offset + 1];
					final Expr e1 = (Expr) _symbol_e1.value;
					final Symbol _symbol_e2 = _symbols[offset + 3];
					final Expr e2 = (Expr) _symbol_e2.value;
					 return new Mod(e1, e2);
				}
			},
			new Action() {	// [51] Exp = NOT CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Not(e);
				}
			},
			new Action() {	// [52] Exp = MINUS CExpr.e
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return new Neg(e);
				}
			},
			new Action() {	// [53] Exp = INT.n
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_n = _symbols[offset + 1];
					final Integer n = (Integer) _symbol_n.value;
					 return new NInt(n);
				}
			},
			new Action() {	// [54] Exp = FLOAT.f
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_f = _symbols[offset + 1];
					final Float f = (Float) _symbol_f.value;
					 return new NFloat(f);
				}
			},
			new Action() {	// [55] Exp = CHAR.c
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_c = _symbols[offset + 1];
					final Character c = (Character) _symbol_c.value;
					 return new NChar(c);
				}
			},
			new Action() {	// [56] Exp = TRUE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new True();
				}
			},
			new Action() {	// [57] Exp = FALSE
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new False();
				}
			},
			new Action() {	// [58] Exp = NULL
				public Symbol reduce(Symbol[] _symbols, int offset) {
					 return new Null();
				}
			},
			new Action() {	// [59] Exp = Lvalue.l
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					 return l;
				}
			},
			new Action() {	// [60] Exp = OPEN_PARENTHESIS CExpr.e CLOSE_PARENTHESIS
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol e = _symbols[offset + 2];
					 return e;
				}
			},
			new Action() {	// [61] Exp = TYPE_NEW Type.t AP OPEN_BRACKET CExpr.e CLOSE_BRACKET opt$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_t = _symbols[offset + 2];
					final Node t = (Node) _symbol_t.value;
					final Symbol e = _symbols[offset + 5];
					 return new New(t, e);
				}
			},
			Action.NONE,  	// [62] opt$Exps = 
			Action.RETURN,	// [63] opt$Exps = Exps
			new Action() {	// [64] Exp = ID.v OPEN_PARENTHESIS opt$Exps.e CLOSE_PARENTHESIS OPEN_BRACKET CExpr.ce CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Node e = (Node) _symbol_e.value;
					final Symbol ce = _symbols[offset + 6];
					 return new Call(v, e, ce);
				}
			},
			new Action() {	// [65] Lvalue = ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_v = _symbols[offset + 1];
					final String v = (String) _symbol_v.value;
					 return new Var(v);
				}
			},
			new Action() {	// [66] Lvalue = Lvalue.l OPEN_BRACKET Exp.e CLOSE_BRACKET
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_e = _symbols[offset + 3];
					final Expr e = (Expr) _symbol_e.value;
					 return new Index(l, e);
				}
			},
			new Action() {	// [67] Lvalue = Lvalue.l DOT ID.v
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_l = _symbols[offset + 1];
					final Node l = (Node) _symbol_l.value;
					final Symbol _symbol_v = _symbols[offset + 3];
					final String v = (String) _symbol_v.value;
					 return new Field(l, v);
				}
			},
			new Action() {	// [68] Exps = Exp.e AP COMMA Exp.ep opt$lst$FP
				public Symbol reduce(Symbol[] _symbols, int offset) {
					final Symbol _symbol_e = _symbols[offset + 1];
					final Expr e = (Expr) _symbol_e.value;
					final Symbol _symbol_ep = _symbols[offset + 4];
					final Expr ep = (Expr) _symbol_ep.value;
					 return new ExpList(e, ep);
				}
			}
		};

 good = true;
	}

	protected Symbol invokeReduceAction(int rule_num, int offset) {
		return actions[rule_num].reduce(_symbols, offset);
	}
}
